### ISSUE TITLE
Heartbeat 2: Develop and align on processes and instructions for the tools we use to track Heartbeat projects

### ISSUE THREAD

**Issue by djst** [mozilla/participation-org#10]
Having a solid process for managing heartbeat projects is crucial to the success of the Participation team.
# Project description

By the end of this Heartbeat cycle, all projects will be updated and maintained using Github issues and it will be clear to everyone how to use the infrastructure. We will also have a list of recommendations for changes we could make to the system to improve the workflow for the future (these recommendations would feed into a future Heartbeat cycle).
# Why
- Having a solid process for managing heartbeat projects is crucial to the success of the Participation team. 
# Primary Goals/Objectives - Success Measures
- All heartbeats are tracked as Issues in GitHub
- Project managers update milestones list throughout a Heartbeat cycle so "outsiders" can follow progress
- 
# Secondary Goals/Objectives
- None
# Deliverables
- Clear educational page summarizing how to use available infrastructure to create, track and update Heartbeat projects
- Document listing recommended changes/improvements to the GitHub infrastructure
- Blog post about our Heartbeat process that feeds into the bigger Participation communication plan
# Team
- Accountable: @djst 
- Consulted: @ppapadeas, @akatsoulas, @comzeradd, @johngian  
- Informed: 
# Milestones (complete before dates)
- [x] Kickoff meeting (@djst, May 14)
- [ ] Publish blog post about our Heartbeat process that feeds into the bigger Participation communication plan (@djst, May 26)
- [ ] Create page somewhere summarizing how we are supposed to use the available infrastructure to create, update and track progress of heartbeat projects (@emmairwin (?) otherwise @djst, May 27)
- [ ] Deliver summary of recommendations for any changes of the tools used (@djst, May 29)
# References
- https://docs.google.com/document/d/1OAJ24FJyNj6aADKEmbAhMrhYFzJQ0cEvy2lp3jIkQB0/edit#
