### ISSUE TITLE
Heartbeat 2: FxAndroid in India: Develop a set of detailed experiments with community leaders that can be run in June, July, August

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#11]
# Project description

Build off initial momentum around Firefox for Android (brainstorm session) during the Indian community meetup. Support support a small set of leaders from the Indian community to develop a tangible series of experiments that can be run in June to August in the community, and help them develop a plan for gaining broad buy-in.

Overall, this is about proving that our communities can bring tangible value to top-line product goals, while bringing value to community members (virtuous circle).
# Primary Goals/Objectives - Success Measures
- Objective 1: There is energy/participation from a core group of 3 people from the India community to define a proposal for the broader community
  - Build a concept for a series of experiments to support Firefox for Android
  - Design a pitch for the larger community
  - Create a strategy for getting community excitement and buy-in
# Secondary Goals/Objectives
- Objective 2: Capture the co-creation process of planning that other communities can use to create product/program focused plans
- Objective 3: MoCo specialized staff are involved with this project (seeing the value of co-creating with smart and motivated volunteers)
# Key hypotheses and how they will be tested
- We can convert the energy from the Task Force meetup into tangible projects
  - If this is true we'll see specific commitments from the Indian community
# Deliverables
- Concept and pitch for a series of experiments to contribute to Firefox for Android in India
- Volunteers from Indian community ready to lead this initiative and build buy-in
- Commitment from MoCo Firefox for Android team member to champion the strategy
# Team
- Owner: @geroter
- Designing engagement: @nukeador @rosanardila
- Consulted: 
# Milestones (complete before dates)
- [X] Schedule kickoff meeting by May 15
- [x] Capture all of the notes that feed this project in one place (George) - May 18
- [x] Contact Indian Community (workshop participants) to get 3 people to help lead this effort, schedule meetings (Rosana) - May 18
- [x] Reach at least 2 MoCo staff working with Firefox Android to support this first phase - May 18
- [x] Strategy meetings have happened - May 25
# References

Notes from India Meetup:
https://india.etherpad.mozilla.org/Mozilla-India-TaskForce-Meetup-May15-FirefoxForAndroid

Initial concept:
https://drive.google.com/open?id=12jT1v5zuFwSmk-Otb-PnvLrK4T1wzxR7TtnEjv5kBkI&authuser=0

From Heartbeat #1:
https://drive.google.com/open?id=1fpeFFfPKOg0xDBFHLCDB1ExRUxXG6ucGX4SiRxgd9Mk&authuser=0

**Comment by geroter** [comment]
# Project description

# Primary Goals/Objectives - Success Measures

# Secondary Goals/Objectives

# Key hypotheses and how they will be tested

# Deliverables

# Team

    Accountable: @geroter
    Consulted: 
    Informed:

# Milestones (complete before dates)

# References

**Comment by geroter** [comment]
Adding a working document to develop the experiment options:

https://docs.google.com/document/d/1brAlmCjeCczjIPIM0CC8oZixZr2GpOXgMFn1Bs6Ha9Q/edit#

**Comment by geroter** [comment]
Adding the working Etherpad for the 4 experiment teams -- links in here for many other reference docs:
https://participation.etherpad.mozilla.org/fennec-india-team

**Comment by AkshayTiwari** [comment]
Hi George,

I updated the pad (
https://participation.etherpad.mozilla.org/android-fsa-marketing-strategy )
. I've given my insights. I'll work with the rest of the team on this as
well.

**Comment by geroter** [comment]
**What was supposed to happen?**
Objective 1: There is energy/participation from a core group of 3 people from the India community to define a proposal for the broader community

```
Build a concept for a series of experiments to support Firefox for Android
Design a pitch for the larger community
Create a strategy for getting community excitement and buy-in
```

Objective 2: Capture the co-creation process of planning that other communities can use to create product/program focused plans

Objective 3: MoCo specialized staff are involved with this project (seeing the value of co-creating with smart and motivated volunteers)

**What did happen?**

12 volunteers (high capacity) are organized around 4 different experiments. Each one has a strategy/plan starting to emerge by the end of this Heartbeat. There isn't really any conversation yet about getting broader community buy-in (that doesn't seem to be a priority, and hasn't been pushed by our team).

4 Staff members from the Android, Marketing and L10N teams are fully engaged.

We haven't been successful at organizing synchronous communication -- this has proved difficult (and there's a question of it's value). Everything has be asynchronous thus far and that's working well).

It was only after inviting involvement from the broader India community that we had people step up, suggesting the existing organizing structures were not the right place for this -- but there's a flag here to consider. This appears to be individuals organizing around ideas versus the community.

Our role as staff (question about how this can be done without us) was to curate and synthesize ideas/energy that came from the community. Once the broad ask was out there, the ideas came in. Once staff organized these into discrete experiments/projects, then involvement from volunteers started to accelerate.

Within the individual experiments:
- volunteers are adding most of the ideas and specific content
- staff are doing a lot of the curation and connecting with staff (though there's been at least some volunteers reaching out directly to staff)

Telegram is better than email for generating energy/momentum once people are in the project. Nothing on IRC.

**What are some improvements?**

Need clearer staff roles and a clearer understanding of what will lead to success.

Need clarity on who owns the project and decisions.

**What should we keep the same in this process?**

On the staff side, being conservative with our involvement -- not driving too much and being patient has yielded a good result.

**What does the next Heartbeat for this project look like?**

Run 4 experiments (maybe 5 as there's a new one) -- get them to the point where they are launching/becoming reality.

Assign 1 Participation team member as a champion/project manager for each experiment -- driving timelines, responsibilities, quality of strategy, connecting with staff in other parts of the organization.

Double-down on this project with lots more staff effort.
