### ISSUE TITLE
Heartbeat 2: Generalize best practices and develop v1 of a playbook for Community Meetups

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#12]
# Why
- Community members need a template agenda for their community meetups
- Community meetups that follow a common structure could help us gather more data to change it and have more impact
- Right now there is not a clearly defined set of goals for community meetups
# Primary Goals/Objectives
- Make it easier to organize a country/region community meetup
- Create a consistent methodology for community meetups
- Provide a systematic way to get feedback from community meetups
- Formulate a clear set of goals for community meetups, both for the Participation team and communities
# Secondary Goals/Objectives
- Spread the word about Mozilla's goals to the community
# Team
- Owner @francjp @deimidis
- Members: @geroter, @brianking, @wquiviger, @rosanardila , @couci 
- Informed: ...
- Others: ...
# Milestones (complete before dates)
- [x] Create a draft agenda (@francjp, due May 26)
- [x] Create a draft post-event survey (@francjp, due May 26)
- [ ] Create a draft set of goals for community meetups (@deimidis, due May 26)
# References
- [Heartbeat 1 - Events](https://docs.google.com/document/d/1Khkeht2RIBczcA2iUX7k0F4j36qMIpiiKrTycQKCyKY/edit#heading=h.tea390qbip2m)

**Comment by deimidis** [comment]
We have this template on the wiki: https://wiki.mozilla.org/ReMo/SOPs/Community_meetup

**Comment by deimidis** [comment]
Just found this code od conduct template. I don't know if we should include something like this in our Playbook, but maybe yes: https://github.com/confcodeofconduct/confcodeofconduct.com

**Comment by brianking** [comment]
That template on the wiki is out of date and somewhat basic. It could act as a good starting point however.

A code of conduct is not one of the key deliverables initially, but definitely something we should include moving forward.

**Comment by deimidis** [comment]
I create this etherpad: https://participation.etherpad.mozilla.org/community-meetups-goals-discussion so we could discuss excersises and best practices to define goals for community events

**Comment by francjp** [comment]
First approach of the agenda (WIP): https://participation.etherpad.mozilla.org/Meetups-Agenda
First approach for a post-survey (WIP): https://docs.google.com/a/mozilla.com/forms/d/13zgc48tbmzvL0a9tVT__xaVxG2_QvDNU2DWua849jNc/edit#

**Comment by francjp** [comment]
## What was supposed to happen?
- We should have a clear agenda for the meeting, with clear objectives and outcomes
- We should apply and test this agenda in the last two meetups (Africa and Balkans)

## What did happen?
- Due to lack of time, and feedback, we only came with an initial agenda draft. Goals need to be reviewed, and we would like to include some logistics guidelines.

## What are some improvements?
- Yes, we change our approach for this kind of things, we need to think more strategically on how we can improve our participation as a team in the meetups.
- We tested the 2 post-event surveys in the Balkans meetup, and in the African meetup. Our intention is to apply that too for the Ecuador meetup, and the Bangladesh meeting.

## What should we keep the same in this process?
- The post-survey is pretty solid. Skeleton of the agenda is clear too.

## What does the next Heartbeat for this project look like?
- If we can review the agenda, and review the debrief of the events, it would be perfect to polish the last details. However, I think that this should be continuously reviewed and improved

**Comment by brianking** [comment]
Issue #50 is the next iteration of this.
