### ISSUE TITLE
Germany Partnerships In Place And Initial Plan Milestones Completed

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#148]
## Goal:

Finalise Participation Partnerships in Germany and build initial successes and momentum.
## Success:

4 new partnerships (2 already on board) made and 90% of milestone(s) tasks are completed.
## Related Issues & Links:
- Meta: #105 
- Previous: #128 
- [High-Level plan](https://docs.google.com/document/d/1-ka6nj50x5ywinIPdUZQj-qqL6cEKOZTkDx-p-BW4Jg/edit?usp=sharing)
- [Building a Larger and Stronger Community in Germany - Detailed Plan for Sept 2015](https://docs.google.com/document/d/1057N3xIgVsgDw-H02y9oK8BaqdFqj1dMLJUnL4v2i3k/edit?usp=sharing)
- [On-the-ground Plan - by Mario](https://docs.google.com/document/d/1M5wJB-KeargQMtiuqIYkGnIQ9yDl139_RBdQU-5s5dU/edit?usp=sharing)
## Roles:

Owner: @brianking 
Involved: @mariobehling
## Required:
- [x] Onboard Mario to Participation Team, LDAP setup, .. (@brianking, small, Due: Sep 15)
- [x] Finalise RejectJS and JSConf participation (@brianking @mariobehling, small, Due: Sep 15)
- [x] Finalise project management cadence (@brianking @mariobehling, small, Due: Sep 15)
- [ ] Talk to more teams and try to get 4 more partners committed (@mariobehling @brianking, medium, Due: Sep 22) 
- [ ] All leader roles are written and actions articulated (@mariobehling with @geroter @brianking, large, Sept 24)
- [x] Support existing German community in building out action plans (@Nukeador @mariobehling @brianking and @MichaelKohler, medium , Due: Ongoing) 
- [ ] Milestone 1 completed (@mariobehling, large, Sept 24)
- [ ] Milestone 2 completed (@mariobehling, large, Oct 2)

**Comment by elioqoshi** [comment]
Would love to be looped in for anything which can be done remotely :) (which is pretty much most of this I guess)

**Comment by MichaelKohler** [comment]
Of course you can count on my support here as well. Are there any plans for an announcement towards community-german@lists.mozilla.org and community-berling@lists.mozilla.org for this?

**Comment by brianking** [comment]
Yes, announcement coming in the next couple of days, just fixing up a couple of loose ends.

Thanks for the offer of help both.

**Comment by MichaelKohler** [comment]
Hi Brian, any update on the info to the mailing lists?

**Comment by brianking** [comment]
4/8 tasks completed, with possibly more to be checked off.

@mariobehling if you can give a short update on the remaining items, in particular:
- Talk to more teams and try to get 4 more partners committed
- All leader roles are written and actions articulated
- Milestone 1 completed (@mariobehling, large, Sept 24)
- Milestone 2 completed (@mariobehling, large, Oct 2

**Comment by MichaelKohler** [comment]
Hi guys, once again asking for an update in terms of officially explaining the community what is going on here. I'd be glad to go ahead and explain what I know but somehow I have the feeling that I don't know everything that Briand and Mario talk about, since I just saw a request for mozilla.berlin as domain which has not been documented anyware else. I'd be glad to support with the message to all German-speaking contributors, just tell me what the plan is and I can come up with mail to the mailing list. Thanks, Michael

**Comment by mariobehling** [comment]
> Talk to more teams and try to get 4 more partners committed

Talking to more teams of people in the office, e.g. idea town, software developers, usability, learning project. There are concerns from teams, that resources to engage with volunteers are limited. We are working with teams and addressing those concerns. Followed up with Rosana about this.

> All leader roles are written and actions articulated

We need to define leader roles also according to the people we are getting onboard. I am following up with George on this as he will be in Berlin soon.

Milestones:
As I started later than originally planned some milestone points are delayed or reshuffled a bit. The main goal of all activities is to get new people onboard and we are progressing well here.

> Milestone 1 completed (@mariobehling, large, Sept 24)

Mostly completed. Some items need to be followed up later, when possible, e.g. Alex is not available in Mozilla office. 

>  Milestone 2 completed (@mariobehling, large, Oct 2

Social media goals have been achieved. An important point to add here: Event activities at RejectJS/JSConf/Makerfaire have been done together with Mozillians. We got lots of new contacts and workshops had huge attendance. Slight delay due to "tech" blocker for newsletter for Berlin region has been solved. Idea is to put it on Mozilla.Berlin and let local volunteers involve step by step.

**Comment by MichaelKohler** [comment]
Hi Mario,

Thanks for the update. Nevertheless it would be good to know if there is any official announcement planned for the community-german mailing list.

Further, to be honest, I'm quite missing the plan on how to integrate new contributors to the community.

Cheers,
Michael

**Comment by MichaelKohler** [comment]
Also I'd be interested in knowing how the mozilla.berlin and Mailchimp integration would be integrated with the overall German-speaking community.

**Comment by brianking** [comment]
Hi Michael,

This is about moving fast and trying new things. The crucial parts, and Mario outlined, is recruiting new leaders and matching them functional areas where we can make an impact and build out as they get deeper into Mozilla. The November moment in time can be a hook, but not a prerequisite.

The integration with community part if not fully thought through yet to be honest, and I ask for patience there. I suggest we get on a call over the next couple of weeks to discuss this. For now the general guidelines are something like ... be welcoming and engaging with new community members.

Yes, we owe the community list an email about this. I will write it before the end of the week.

Thanks for the nudge.
