### ISSUE TITLE
Heartbeat 2: Design Participation sessions + volunteer engagement for Whistler work week

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#18]
# Project description

Background: Participation Team role to have teams prepare for and engage volunteers effectively in Whistler.  We are taking responsibility for making sure that goes well.
# Primary Goals/Objectives - Success Measures
- Objective 1: Ensure teams are using best practice on engaging/preparing volunteers at Whistler
- Objective 2: Schedule, plan activities for the Participation Team during Whistler
  - Plan activities that the Participation Team is engaging other teams in
- Objective 3: Set ourselves up to measure the impact/value of volunteer involvement
# Secondary Goals/Objectives
- Objective 4: Creating visibility of volunteer participation at Whistler in the lead-up to the event
# Key hypotheses and how they will be tested
- If a functional team considers volunteer participation early they will gain more value out of this
  - Reported value from workweek (volunteers + teams)
- There is demand for Participation team services within the organization
  - # of requests back
# Deliverables
- Synthesize notes and turn them into best practice/playbook
- Email communication/newsletter out to all team leaders with some best practice on volunteer set-up/engagement
- Draft agenda for Participation Team during work week
- Build and communicate our "Design for Participation" consulting offering to functional/product teams
- Momentum Plan, identify strategy for comms/engaging people after the event.
- Confirm Participation experts who will be joining us at Whistler
# Team
- Owner: @brianking 
- Design for Participation (design/drive): @deimidis  @emmairwin @geroter
- Participation Agenda: @geroter @brianking @francjp
- Comms/coordination/best practice: @brianking @deimidis @francjp
- Consulted: @nukeador Rosana
# Milestones (complete before dates)
- [X] Schedule kickoff meeting by May 15
- [x] Agenda template for Participation team - May 22
- [x] Basic "Design for Participation" concept available for feedback - May 20
- [ ] Table of Contents of playbook - May 22
- [ ] Email communication goes out (to volunteers/teams) - May 29
# References

Project description:
https://drive.google.com/open?id=1NL26s8iTMp4dMYN6GsmVNLIFotumVE99-dLWZQbg0a0&authuser=0

Best practice notes:
https://docs.google.com/document/d/1OsdMejNwGLDW0V2n_WO81MmrEqj6lDhlbqHbyUMlYoE/edit

**Comment by MichaelKohler** [comment]
the "Best practice notes" require permission, just saying ;)

**Comment by brianking** [comment]
Agenda doc: to be hacked on:

https://docs.google.com/document/d/1KSRglmMoBCqEpFr60ak8ojWWkcGDGfGf8QNTDSkdyHw/edit

**Comment by geroter** [comment]
Visual agenda:
https://docs.google.com/spreadsheets/d/1fMBaO18F9QoI6Bfq_hmLxxnwSmP5vBCfgGOTrRX3le4/edit#gid=0

**Comment by emmairwin** [comment]
Preparing, Designing and Practicing Document Share : https://docs.google.com/document/d/17-OTi-5sKZc1Kv2axAzxP-8KZ__rV6sJQziltj-pe54/edit#heading=h.udv0no43dyd0

**Comment by geroter** [comment]
Further framing of  "common" sessions via invites to the rest of the organization:

https://docs.google.com/document/d/1roRewXhAZJx9afBOmutkAOcVVjFLGEFUhDn9fGodgMM/edit#heading=h.q0ohj0y36552

**Comment by brianking** [comment]
### What was supposed to happen?
- Draft Participation agenda for Whistler
- Create framework for Participation consulting at Whistler
- Creation of best practices document for working with volunteers at the workweek, and shared with leads of teams who will have 

### What did happen?
- Draft Participation agenda for Whistler
- Create framework for Participation consulting at Whistler

### What are some improvements we should make?
- Coordinate better as a team

### What should we keep the same in this process?
- Getting input from a broad range of stakeholders

### What does the next Heartbeat for this project look like?
- Finish session designs and best practices and get the email communications sent out.
