### ISSUE TITLE
Heartbeat 2: Develop a series of goals/focus areas for energizing and aligning Reps/Regional Communities, and design a communication and coaching process

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#20]
Gather most impactful initiatives volunteers can be currently part of and display them in a way it's easy to find, contribute and understand how they are tied to global organizational goals.
# Project description

Gather most impactful initiatives volunteers can be currently part of and display them in a way it's easy to find, contribute and understand how they are tied to global organizational goals.
# Why
- Currently most volunteers are not aware of organizational goals.
- They don't know which initiatives are currently open for participation.
- They don't know which ones are more impactful and tied to current org goals. 
# Primary Goals/Objectives
- Gather all active/current initiatives/campaign/projects people can contribute to.
- Prioritize based on org goals and team goals.
- Define a communication on how to present them in a easy/attractive way.
- After this heartbeat: Measure if we have an increase of participation in the top priority initiatives we defined.
# Secondary Goals/Objectives
- Mix this Hearbeat with «Best practices» on how to work with volunteers on Whistler
# Team
- Owner @nukeador
- Members: @rosana, @brianking @deimidis @couci
- Informed:
- Others:
# Milestones (complete before dates)
- [x] Friday May 22th: List of all current activities.
- [x] Monday May 25th: Meet again and agree on priorities.
- [x] Friday May 29th: A wiki page with at least top 3 initiatives.
- [x] Friday May 29th: Communication plan rolled out.
# References

**Comment by nukeador** [comment]
Updated content after kickoff meeting.
