### ISSUE TITLE
Create a budget tracking system for the Participation team

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#218]
## Goal:

Create a tracking budget system for the current expenses of the Participation team (included sub-teams and individuals expenses)
## Success:
- Create a tracking system
- Create reports for big scale events
## Related Issues & Links:
#186

Meta #181 
## Roles:

Owner: @couci
Involved: @francjp 
Informed: @rosanardila @geroter 
## Required:
- [x] Create a list with tools and reports @couci needs access in order to track fully the expenses e.g egencia (@couci [medium], Due: Nov 19th)
- [x] Create a tracking system based on the current tools we are using (@couci [large], Due: Nov 29th)
- [x] Work on big scale event budget reports (@couci @francjp  [medium], Due: Dec 3rd)

**Comment by couci** [comment]
sent the tracking draft to @geroter waiting for feedback

**Comment by couci** [comment]
draft for big scale events has been shared with @francjp for feedback
