### ISSUE TITLE
Heartbeat 2: Kick off Reps 2.0 Council initiatives

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#24]
# Project description

At the meeting in Paris the Reps council decided to focus their energy on three main initiatives to drive change. This heartbeat focuses on kicking off the “planning” initiative to help the Council drive change by helping Reps to plan better their activities and initiatives.
# Primary Goals/Objectives - Success Measures
- Get buy-in and participation from the Council to drive this initiative
- Design the “planning” initiative with the Council members and get first round of feedback from mentors
# Secondary Goals/Objectives
- Activate Council and members to drive this initiatives
# Key hypotheses and how they will be tested
- Reps are frustrated by the delay of the decision from Council. This makes logistics and events a hassle in general. Although the Council has optimized processes there never seems to be enough time. By getting Reps to plan earlier and do long-term plans we think that the impact of the activities can be increased and the logistic can be smoother.
# Deliverables
- An initiative within the Reps program for earlier planing
- First data on how planing is usually made
# Team
- Owner: @rosanardila
- Members: @nukeador , @couci 
- Informed: @emmairwin 
# Milestones (complete before dates)
- [x] May 20th: present Council initiative, get interested Council members together
- [ ] May 26th: send draft to the mentors list and get feedback
- [ ] May 26th: get data around planing
- [ ] May 28th: present initiative to Reps in the Reps general call

**Comment by brianking** [comment]
@rosanardila Can this one be closed?
