### ISSUE TITLE
Heartbeat 2: Agile Participation Infrastructure

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#25]
# Project description

Extending from Heartbeat 1, this project solidifies the documentation of policy and procedure around the new infrastructure, while deploying one application on it.
# Primary Goals/Objectives - Success Measures
- Cleanup and run-test the Policy and Procedure Documentation
- Deploy one application to the new infrastructure
- Develop deployment and management scripts (Ansible)
# Secondary Goals/Objectives
- Involve Community Ops 
# Key hypotheses and how they will be tested
- Robust and documented agile deployment techniques and infrastructure will enable faster deployment and lower maintenance for our projects.
# Deliverables
- Policy and Procedure documentation
- Ansible scripts
- One project to the new infrastructure
# Team
- Owner: @ppapadeas
- Members: @johngian , @comzeradd , @akatsoulas 
# Milestones (complete before dates)
- [x] May 18th: First iteration of Ansible configuration
- [x] May 22th: First test docker instance deployment
- [ ] May 26th: Policy Documentation done
- [x] May 27th: Procedure Documentation done
- [x] May 29th: Mozbugsprints deployed on new infrastructure

**Comment by johngian** [comment]
Ansible configuration is being tracked here [1] for now.
What we have implemented so far is a local deployment of a HA setup.
- 3 master nodes running
  - `mesos-master`
  - `zookeeper`
  - `marathon`
  - `chronos`
- 3 slave nodes running
  - `mesos-slave`
  - `docker`

[1] https://github.com/johngian/partinfra-mesos

**Comment by johngian** [comment]
This PR introduces the docker functionality:
https://github.com/johngian/partinfra-mesos/pull/4

With the changes above, we successfully deployed a PoC docker-based test app.

**Comment by ppapadeas** [comment]
Dockerized reclama (mozbugsprints) for deployment. https://github.com/mozilla/reclama/pull/17

**Comment by ppapadeas** [comment]
https://gist.github.com/johngian/fb9cb98dcbacddab766f Deployment commands published

**Comment by ppapadeas** [comment]
## What was supposed to happen?
- Cleanup and run-test the Policy and Procedure Documentation
- Deploy one application to the new infrastructure
- Develop deployment and management scripts (Ansible)

## What did happen?

We experimented more on the infrastructure deployment and on streamlining the procedure to enable even volunteer contributors to deploy apps in our new infrastructure.

As this was a new effort (devops & webops wise) for the team we spent a lot of time reading and gathering best practices around Mozilla and the broader community.

We also dockerized one app (reclama) for testing and production deployment purposes.

## What we learned?

We learned that deploying production ready infrastructure from scratch can be time consuming especially without dedicated WebOps and DevOps people on it. 

Lot's of learning and growing happened but we still have margins for improvements and investment especially if we choose to commit to this infrastructure for the long-run (and for more demanding projects like mozillians.org and reps.mozilla.org)

## What are some improvements?

Working more with other Mozilla teams that are facing the same problems and deployment requirements would help more. We could have done an even better work on that.

## What does the next Heartbeat for this project look like?

On version 3 for this project we would like to focus more on production deployment and move 2 more applications to our new infrastructure. Also finalize policy with community to ensure broader volunteer participation.
