### ISSUE TITLE
H2: Bangladesh Community meetup + Webmaker planning

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#27]
# Project description

The BD community faces some challenges. To take advantage of the incredible potential of the community, we want to help them build a new leadership vision and work together to make a plan for the rest of the year and beyond.
# Why
- The BD community is growing, both in terms of numbers and activity, and we need to work with them to address scaling challenges.
- The current leadership model is proving to be challenging for some of the community, and we would like to build a more distributed leadership structure into the community.
- The Webmaker team is launching a big initiative in Bangladesh, and we (the Participation team) want to support them and setup the community to work towards the common goal of making the campaign a success.
# Primary Goals/Objectives
- Build a **distributed leadership model** in the BD community
- Setup community to support Webmaker campaign in BD.
# Secondary Goals/Objectives
- Re-energise the BD community
# Team
- Owner @brianking 
- Members: @deimidis , @francjp , @geroter, @rosanardila 
- Informed: @williamq, @emmairwin 
- Others: 
# Milestones (complete before dates)
- [x] Setup Reps Event page and open rough budget request (@francjp, due May 22)
- [x] Finalise venue for meetup (@francjp, due May 22)
- [x] List of attendees + save the date email sent (@francjp, due May 22)
- [ ] Determine travel needs to attendees (@francjp, due May 22)
- [x] Initial draft of Participation team strategy (@brianking, due May 21)
- [x] Emails to different Webmaker teams outlining Participation strategy and setup call to discuss further (@brianking, due May 22)
- [ ] Agenda first-pass (@brianking, @geroter, @rosanardila, due May 26)
# References
- Bangladesh plan for June 1st-18th: https://docs.google.com/document/d/1hnpXwboPWv_VLa_NiKHYDnWyIB9IjEc89adoKgOuvPY/edit?usp=sharing

**Comment by brianking** [comment]
Call with Webmaker team today to work on common plan for Bangladesh visit.

**Comment by brianking** [comment]
(Webmaker) Bangladesh plan for June 1st-18th : https://docs.google.com/document/d/1hnpXwboPWv_VLa_NiKHYDnWyIB9IjEc89adoKgOuvPY/edit?usp=sharing

Community Planning Meetup 2015 - Bangladesh : https://docs.google.com/document/d/1EsDcKqhOlMWdOm-9iv8bMm6U9bF-yciv_xHr1MqhIqU/edit?usp=sharing

**Comment by brianking** [comment]
### What was supposed to happen?
- All logistics for the meetup should have been locked down by the end of the heartbeat. This includes such things as travel bookings, venue secured, and so on.
- The Participation should have collaborated with the Webmaker team to discuss how each can best support their goals in Bangladesh. The Participation goal is community health and distributed leadership, and the Foundation goal is to build out a community team and run a Webmaker launch campaign.
- A Draft Agenda published

### What did happen?
- The venue was secured
- The community was given a "save the date" for the weekend, and a shortlist of attendees was selected. This is pending final approval by the Participation team
- The Participation and Webmaker team met and discussed goals and how to work together
- A partial draft agenda was made

### What are some improvements we should make?
- More lead in time for event - always a known issue. We took this opportunity as we saw it and closed in on dates as early as we could
- Being clearer on goals earlier on. While we had a broad idea of goals for community health and the Webmaker launch, getting specific earlier would have benefited us more

### What should we keep the same in this process?
- Integrated working across the organisation
- This includes working closely with the community

### What does the next Heartbeat for this project look like?
- Finishing the agenda and planning different scenarios for the meetup
- The meetup
- Post-meetup summary + next steps document
- Plan for Participation support of the Webmaker launch

In general I would say this heartbeat gained momentum a little late into the period because of other commitments of the Participation team. The main lesson learned is that somehow momentum has to start earlier and continue throughout the whole period.

**Comment by brianking** [comment]
Issue #57 is the next iteration of this.
