### ISSUE TITLE
H2: Community Health Surveys

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#28]
# Project description

Basic Summary: Publish community surveys with the basic result desired being a 'State of Communities' report with recommendations on how to better support our communities moving forward.
# Why

We want to find out more about our regional communities, namely:
- Are we supporting communities well enough?
- What are the communities that need the most support and guidance from us?
- What are the key strengths and weaknesses of each community?
- What functional areas are communities having the biggest impact on by region?
- What governance structures are working and which ones aren’t?
- What patterns can we see in terms of governance and leadership distribution?
- Are communities wanting physical spaces to be more effective?
- Are communities satisfied with the regional support they are getting?
- What are communities asking for that will better facilitate their work?
- Do the communities have a plan to grow/work?
- Are the communities stagnated, growing or decreasing?
# Primary Goals/Objectives
- Publish the surveys
- [Follow-up] Produce a 'State of Communities' report
- [Follow-up] Come up with at lest 3 recommendations for better support for our communities
# Secondary Goals/Objectives
- With regional manager leaving, pay particular attention to Asia to allow sentiment and feedback to feed into our plan.
# Team
- Owner @brianking
- Members: @rosanardila, @nukeador 
- Informed: @geroter 
- Others: ...
# Milestones (complete before dates)
- [ ] Gather final feedback from Rebecca Weiss on the questions (@brianking, due May 26)
- [ ] Make final pass on question (@brianking,, @nukeador, @rosanardila  due May 27)
- [ ] Build a test group to try out the survey on before publishing (@brianking,, @nukeador, @rosanardila, due May 28)
- [ ] Publish
# References
- List any relevant documents, etc.

**Comment by brianking** [comment]
@rosanardila assigned this one to you, not sure what you want to do with it now.

**Comment by rosanardila** [comment]
Hi Brian, the survey is out and we're gathering the data in form of the dashboard an country reports. We didn't include all the questions, but this is a first take on it. It will surely evolve. Since the survey (and partial results) is out closing this.
