### ISSUE TITLE
Prepare a Roadmap for community meetups on Q2

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#341]
## Goal:

Define and select the communities that will have a community meetup in Q2
## Success:

At least 3 communities will have their meetups in Q2, or at the end of Q1
## Roles:

Owner: @francjp
Involved: @deimidis, @rosanardila, @williamq
## Required:
- [x] Create a list of possible communities (@francjp [small], Due: Feb 15th) 
- [x] Contact the communities listed and start the planning (all, [medium], Due: Feb 26th) 
- [x] Define dates and locations of the meetups (@francjp, @deimidis, @rosanardila  [medium], Due: Mar 9th)

**Comment by francjp** [comment]
First draft of the 2016 calendar: https://docs.google.com/spreadsheets/d/14rN0kHQnNbOF7sc0AWQj5NmEnO2yU9P8jrktwQjsHRY/edit?usp=sharing

Need to review options.

**Comment by geroter** [comment]
Would like a column in the table about who is taking what role. Staff,
volunteers, etc.

Please see the Participation strategic direction for 2016 ... at the end
there's a table with an events framework that build of last year's work by
@wquiviger -- that will be helpful as a reference

**Comment by francjp** [comment]
Moving to the following heartbeat, and updating the deadlines

**Comment by francjp** [comment]
Only one meetup confirmed (Brazil).

Need to define strategy about other community meetings, but it will be likely to define on Q3.

In any case, this issue was also useful to start defining a community events calendar.
