### ISSUE TITLE
RepsNext: Meta Working Group

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/participation-org#347]
## Goal:

The goal of this working group is to track and answer the broad questions we have around overall, program-wide topics
## Success:

All overall questions are answered and we have a plan on how things should work after that.
## Related Issues & Links:
- META: #303
- [Discourse topic](https://discourse.mozilla-community.org/t/working-group-meta/7051/2)
- Meeting notes: [1](https://discourse.mozilla-community.org/t/working-group-meta/7051/5?u=mkohler)
## Roles:
- Owner: @bacharakis @MichaelKohler
- Involved: @Mte90
## Required:
- [x] Start discussion: Figure out where the role of the Reps portal is, how many resources there are for changes from the dev side → open a discourse topic (@Mte90, [medium], Due: Feb. 22)
- [x] Start discussion: Identify a plan on how to combine different specializations (this might change over the time with the work of the other groups)  (@MichaelKohler, [medium], Due: Feb. 22)
- [x] Organize followup meeting to assign the next steps (@MichaelKohler, [medium], Due: Feb 23)
- [x] Definition of the process to join a specific specialization (general level) (@Christos, [medium], Due: March 10)
- [x] Figure out a plan on how to do recognition to avoid specialization to be the only recognition (??, [medium], Due: March 20th)
- [ ] Figure out the role of the reps portal in the new settings (@Mte90, [medium], Due: March 20th)
- [x] Define a plan on how to handle countries with only one/no Rep → not covering all specializations  (??, [medium], Due: March 20th)
- [x] Define a suggestion on how to find a specific Rep with a certain kind of specialization (also consider MoCo teams, outside of Reps) (??, [medium], Due: March 26th)
- [x] Have final version of our answers (@MichaelKohler, [medium], Due: March 30th)

**Comment by ioana-chiorean** [comment]
Do you need some help on this one @MichaelKohler?

**Comment by MichaelKohler** [comment]
> Do you need some help on this one @MichaelKohler? 

@ioana-chiorean, of course, I would never say no to help :) I will start a conversation on Discourse regarding the combination of specializations tonight, maybe you could jump in there as a first step?

**Comment by ioana-chiorean** [comment]
Sounds like a plan :tada:

**Comment by Mte90** [comment]
For the Community Leadership track we are working to create a new survey for understand some feelings from the reps.
I think that we can join the force to create an unique survey.

Ticket: https://github.com/mozilla/participation-org/issues/374
Our working survey: https://docs.google.com/document/d/15GK_FTIPLTupf06ONdxH8szhNGiHT7HJeH3dTeWNxiQ/edit?usp=sharing

We can discuss that on the next meeting.

**Comment by MichaelKohler** [comment]
The meeting notes from today have several next steps that are not directly documented above, but they would only clutter the "Required" section IMHO. All of these are "baby steps" towards the tasks defined above. https://discourse.mozilla-community.org/t/working-group-meta/7051/26?u=mkohler

**Comment by MichaelKohler** [comment]
Proposal: https://docs.google.com/document/d/1nasMyLtDj9YV0Dk_pqhMyw75ETCJqU9MSgJqS3Uirgk/edit?usp=sharing

**Comment by MichaelKohler** [comment]
@mte90 will do the Reps portal discussion seperately

**Comment by Mte90** [comment]
I started to write the document about Reps portal but is a draft and unfinished. 
https://docs.google.com/document/d/1rghXJw4ulgmvFlEnm75p84F5KdXYqKYkTIE2F_grYaw/edit
