### ISSUE TITLE
Reps Weekly Call - February 25th, 2016

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#353]
## Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana_chiorean, [small], Due: Feb 25th)
- [x] Council updates - (@ Reps Council, [medium], Due: Feb 25th )
- [x] Fossasia - (@francjp, [medium], Due: Feb 25th)
- [x] Help me with my project - call for entries (@ioana_chiorean, [small], Due: Feb 25th)
- [x] Topic 1 - Brazil Meetup #304 (@deimidis , [medium], Due: Feb 24th)
- [x] Topic 2 - New NDA process #292 (@lucyeoh , [medium], Due: Feb 24th)
- [x] Topic 3 - Community Dashboard for Q4/2015 #269 (@couci , [medium], Due: Feb 24th)
## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-25-02-16) (,@couci, [small], Due: Feb 24th)
- [x] [Discourse post](https://discourse.mozilla-community.org/t/weekly-call-2016-02-25/7312)  (@ioana_chiorean, [small], Due: Feb 25th)
- [x] mail on reps- general  (@ioana_chiorean [small], Due: Feb 25th)
- [x] telegam and Social Media - FB and TW  (@ioana_chiorean,@couci, [small], Due: Feb 25th)
- [x] Send invites to speakers (@ioana_chiorean,@couci, [small], Due: Feb 24th)
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana_chiorean,@couci, [small], Due: Feb 28th)
- [x] Post meeting notes (@ioana_chiorean,@couci, [small], Due: Feb 28th)
- [x] Mail Shout-Outs to be shared on SM (@ioana_chiorean,@couci, [small], Due: Feb 28th)

**Comment by couci** [comment]
Lucy has confirmed for this week's call

**Comment by ioana-chiorean** [comment]
Thanks @couci. Any decision for the dashboard?
@deimidis  - can you jump in the call?

**Comment by couci** [comment]
Hey @ioana-chiorean yes I will give a small presentation on how new dashboard looks like and what is the future with that project.

**Comment by deimidis** [comment]
Sorry @ioana-chiorean, we don't have too many news to comment right now. We are discussing dates, I prefer to talk with that defined

**Comment by couci** [comment]
taking out the brazil meet-up, adding Fossasia on @francjp

**Comment by couci** [comment]
agenda can be found here https://public.etherpad-mozilla.org/p/remo-call-25-02-16

**Comment by ioana-chiorean** [comment]
All done. Closing this.
