### ISSUE TITLE
Reps Weekly Call - March 10th, 2016

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#382]
## Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

⬅️ #378 
➡️ #384
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, [small], Due: March 10th)
- [x] Council updates - (@ Reps Council, [medium], Due: March 10th)
- [x] Events - (@francjp, [medium], Due: March 10th)
- [x] Help me with my project - call for entries (@ioana-chiorean, [small], Due: March 10th)
- [x] 🔛 Topic 1 -  Participation infrastructure ( @ioana-chiorean, @ppapadeas, @mozilla/participation-infrastructure [medium], Due: March 9nd) 
- [x] 🔃 Topic 2 - Brazil Community Meetup(@ioana-chiorean, [medium], Due: March 9th) #366
- [x] 🔃 Topic 3 - Mexico Community plan (@ioana-chiorean, [medium], Due: March 9th) #368 #306
- [x] 🔛  Topic 5 - Slovenian Meetup (@ioana-chiorean [medium], Due: March 9th)  - Speaker: @GapsoNtm [Reps Event](https://reps.mozilla.org/e/1st-mozilla-community-meetup-in-2016/) 
- [x] 🔃 Topic 6 - Mozilla Celtic Hackathon (@ioana-chiorean [medium], Due: March 9th) - [Reps Event](https://reps.mozilla.org/e/mozilla-celtic-hackathon/)
- [x] 🔛 Topic 7 - Mozilla's new Brand Look - Tim Murray (@ioana-chiorean [medium], Due: March 9th) - More details [here](https://blog.mozilla.org/creative/2016/03/04/mozilla-is-getting-a-new-brand-look/).
- [x] 🔛 Topic 8 - Campus Campaign updates - Lucy (@lucyeoh [medium], Due: March 9th) - More details [here](https://github.com/mozilla/participation-org/issues/356/).

Status
🔜 - we can present next week
🔃 - we need to see when we can present
🔛 - topic will be presented in the call
❓ -  topic needs to be confirmed for the call. 
## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-10-03-16) (@ioana-chiorean,@couci, [small], Due: March 9th) 
- [x] Discourse post  (@ioana-chiorean, [small], Due: March 9th)
- [x] mail on reps- general  (@ioana-chiorean [small], Due: March 10th)
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean,@couci, [small], Due: March 10th)
- [x] Send invites to speakers (@ioana-chiorean,@couci, [small], Due: March 10th)
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean,@couci, [small], Due: March 12th)
- [x] Post meeting notes (@ioana-chiorean,@couci, [small], Due: March 12th)
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean,@couci, [small], Due: March 12th)

**Comment by ioana-chiorean** [comment]
Agenda created - https://public.etherpad-mozilla.org/p/remo-call-10-03-16

**Comment by ioana-chiorean** [comment]
Added links for all topics ( except 1) and contacted the owners to check availability.

**Comment by ioana-chiorean** [comment]
Gasper (@GapsoNtm) just confirmed he will attend the call and talk about Slovenian Meetup.

**Comment by couci** [comment]
@ppapadeas has also confirmed so I'm adding him

**Comment by ioana-chiorean** [comment]
:tada:

**Comment by couci** [comment]
Events will be non verbal today since @francjp can not attend

**Comment by couci** [comment]
Tim has confirmed too

**Comment by ioana-chiorean** [comment]
All sub-tasks are done so I'm closing the issue
