### ISSUE TITLE
Reps Weekly Call - March 17th, 2016

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#384]
## Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

⬅️ #382 
➡️ #391 
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, @couci, [small, medium, large], Due: March 16th )
- [x] Council updates - (@ Reps Council, [medium], Due: March 16th )
- [x] Events - (@francjp, [medium], Due: March 16th )
- [x] Help me with my project - call for entries (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] ❌ Topic 1 - Brazil Community Meetup(@ioana-chiorean, [medium], Due: March 16th) #366 #397
- [x] ❌ Topic 2 - Mexico Community plan (@ioana-chiorean, [medium], Due: March 16th) #368 #306 #399
- [x] ✅ Topic 3 - Mozilla Celtic Hackathon (@ioana-chiorean [medium], Due: March 16th) - [Reps Event](https://reps.mozilla.org/e/mozilla-celtic-hackathon/)
- [x] 🔜 Topic 4 - Flisol  (@ioana-chiorean [medium], Due: March 16th) - Details #369 #396 by @deimidis @francjp 
- [x] ❌ Topic 5 - Plan for community spaces (@ioana-chiorean [medium], Due: March 16th) - Details #313 by @williamq 
- [x] 🔜 Topic 6 - Events Playbook (@ioana-chiorean [medium], Due: March 16th) - Details #339 & #394  by @francjp 
- [x] ❌ Topic 7 - "Bootstrapping your project" event kit for Connected Devices (@ioana-chiorean [medium], Due: March 16th) - Details #319 by @williamq @ensowhat 
- [x]  ❌ Topic 8 - e10s - Jeff Griffiths  (@ioana-chiorean [medium], Due: March 16th)
- [x]  ✅  Topic 9 - [FOSSASIA](https://discourse.mozilla-community.org/t/mozilla-at-fossasia-2016/7302) - @ariestiyansyah  (@ioana-chiorean [medium], Due: March 16th)
- [x]  ✅  Topic 10 - London all-hands - @emmairwin  (@ioana-chiorean [medium], Due: March 16th)

Status
🔜  - we can present next week
🔃 - we need to see when we can present
✅ - topic will be presented in the call
❔ -  topic needs to be confirmed for the call. 
❌ - not gonna be presented in the call. 
## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-17-03-16) (@ioana-chiorean,, [small], Due: date )
- [x] [Discourse post ](https://discourse.mozilla-community.org/t/weekly-call-2016-03-17/7644)(@MichaelKohler, [small], Due: March 16th )
- [x] mail on reps- general (@MichaelKohler,  [small], Due: March 16th )
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean, [small], Due: March 16th )
- [x] Send invites to speakers (@ioana-chiorean, @couci, [small], Due: March 16th )
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean, [small], Due: March 20th )
- [x] Post meeting notes (@ioana-chiorean, [small], Due: March 20th)
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean, [small], Due: March 20th )

**Comment by ioana-chiorean** [comment]
We confirmed Topic 3 - Stephen - "I'll give it a shot!  It's normally during work hours but it's Patrick's day this Thursday."

**Comment by ioana-chiorean** [comment]
Pinged council, Francisco and most of the potential speakers. Will update this when I will receive replies.

**Comment by ioana-chiorean** [comment]
@francjp replied and we will check for Topic 4 - FLISOL in 2-3 weeks and for Topic 6 - Events Playbook in 2 weeks.

**Comment by MichaelKohler** [comment]
I've announced the meeting on reps-general and Discourse: https://discourse.mozilla-community.org/t/weekly-call-2016-03-17/7644

**Comment by ioana-chiorean** [comment]
No reply at Topics : 1, 2, 5, 7, 8.
I will follow up in time for the next meeting.

**Comment by ioana-chiorean** [comment]
All done :tada: :heavy_check_mark:

**Comment by ioana-chiorean** [comment]
All done :tada: :heavy_check_mark:
