### ISSUE TITLE
Education at Mozilla Community takes first steps

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#389]
## Goal:

Based on research, and call-feedback first steps for the Education Community at Mozilla are proposed and first-steps are being by community leaders on community goals.
## Success:
- Proposal for setting up Education at Mozilla community is shared, for feedback and iteration
- First steps to test two primary hypothesis (one being about connecting people to Mozilla)  have begin.
## Roles:

Owner:  @emmairwin
Involved: @asdofindia  @jgmac1106 and many others 
## Required:
- [x] Summarize feedback on next-steps based on recent calls, research and project needs (@emmairwin, Due: March 18th) 
- [x] Based on feedback propose 'first steps' (@emmairwin, Due: March 24th) 
- [x]  With community leads, setup for success and launch 'first steps' (@emmairwin and others TBA , Due: March 31 )

**Comment by jgmac1106** [comment]
Can you link to etherpad from the calls as well?

**Comment by fayepal** [comment]
Commenting here to participate. I think you have tagged a different Akshay, @emmairwin. ;)

**Comment by emmairwin** [comment]
Thanks Faye !   Ugh I hate when I get the wrong username.  udpating!

**Comment by emmairwin** [comment]
Yes - resources!  Thanks Greg (ordered by most recent)

Etherpad:  https://public.etherpad-mozilla.org/p/education-community
Slide Deck: https://docs.google.com/presentation/d/1GWV01KV6Ykf0NdlqPKlWfmZ89YuFZpUpTiEqqYuAQtc/edit#slide=id.p
Interview Summary:  https://docs.google.com/document/d/1wz4cP3whStE0qeqxOdJ1zIv4c2N63pFxszyFqVhh3Nw/edit

**Comment by emmairwin** [comment]
Feedback needed, for 'soft' launch Monday.

https://discourse.mozilla-community.org/t/teaching-training-community-proposal/7708

**Comment by emmairwin** [comment]
Community framework setup, first call for launch next week  
https://discourse.mozilla-community.org/t/teaching-training-community-proposal/7708/8

**Portal**: http://mozilla.github.io/community-teaching-training/

**Tasks**: https://waffle.io/mozilla/community-teaching-training

**Chat:** https://discourse.mozilla-community.org/t/rocket-chat/7722/2

**Community Call**

2 calls on March 30 (although one falls on 31 in some time zones)

See Discourse link for Google Calendar Invites

AGENDA:

https://public.etherpad-mozilla.org/p/community-teaching-learning-1

**Comment by chrisdavidmills** [comment]
It is so nice to see this project underway. I'm throwing my hat in ring on behalf of the MDN Learning Area (https://developer.mozilla.org/en-US/Learn.) I'd love to help work towards encouraging contribution to it.

**Comment by emmairwin** [comment]
Thanks @chrisdavidmills will follow up.  
Closing this for this heartbeat.

**Comment by ioana-chiorean** [comment]
@emmairwin do you think we can share more about this in a Reps Call? cc @couci
