### ISSUE TITLE
Reps Weekly Call - March 24th, 2016

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#391]
## Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

⬅️ #384
➡️ #401
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] Council updates - (@ Reps Council, [medium], Due: date )
- [x] Events - (@francjp, [medium], Due: date )
- [x] Help me with my project - call for entries (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] ❌ Topic 1 - Brazil Community Meetup(@ioana-chiorean, [medium], Due: March 23rd) #366 #397
- [x] ❌ Topic 2 - Mexico Community plan (@ioana-chiorean, [medium], Due: March 23rd) #368 #306 #399
- [x] ❌ Topic 3 - Plan for community spaces (@ioana-chiorean [medium], Due: March 23rd) - Details #313 by @williamq 
- [x] ❌ Topic 4 - "Bootstrapping your project" event kit for Connected Devices (@ioana-chiorean [medium], Due: March 23rd) - Details #319 by @williamq @ensowhat 
- [x] ❌ Topic 5 - Diversity and Inclusion by @rara79 and Larissa Shapiro (@ioana-chiorean [medium], Due: March 23rd)
- [x] ✅ Topic 6 - Mozilla Madagascar Online Presence by @mariot (@ioana-chiorean [medium], Due: March 23rd) - Details: https://github.com/mozilla/participation-leaders-accountability/issues/28
- [x] ✅ Topic 7 - Updates about Mozilla Hungary by @flaki (@ioana-chiorean [medium], Due: March 23rd) Details: https://github.com/mozilla/participation-leaders-accountability/issues/24
- [x] 🔜 Topic 8 - Mozilla Tunisia Updates by @ZaafouriFF (@ioana-chiorean [medium], Due: March 23rd) Details: https://github.com/mozilla/participation-leaders-accountability/issues/53 and https://github.com/mozilla/participation-leaders-accountability/issues/47 and https://github.com/mozilla/participation-leaders-accountability/issues/48 
- [x] ❌ Topic 9 - WebVR news by @end3r  and @rabimba (@ioana-chiorean [medium], Due: March 23rd) Details: https://github.com/mozilla/participation-leaders-accountability/issues/23 and https://github.com/mozilla/participation-leaders-accountability/issues/12
- [x] ✅  Topic 10 - Technical contributors & speakers, connected devices, women in MozPune by @ShaguftaMethwani  (@couci [medium], Due: March 23rd) - Details: https://github.com/mozilla/participation-leaders-accountability/issues/42
- [x] ❌ Topic 11 - MozPH Participation Portal by @fayetandog (@couci [medium], Due: March 23rd) - Details: https://github.com/mozilla/participation-leaders-accountability/issues/33

Status
🔜  - we can present next week
🔃 - we need to see when we can present
✅ - topic will be presented in the call
❔ -  topic needs to be confirmed for the call. 
❌ - not gonna be presented in the call. 
## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-24-03-16) (@ioana-chiorean, [small], Due: March 23rd )
- [x] [Discourse](https://discourse.mozilla-community.org/t/weekly-call-2016-03-24/7737) post (@ioana-chiorean, @couci, [small], Due: date )
- [x] mail on reps- general (@ioana-chiorean, @couci, [small], Due: date )
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Send invites to speakers (@ioana-chiorean, @couci, [small], Due: date )
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Post meeting notes (@ioana-chiorean, @couci, [small], Due: date )
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean, @couci, [small], Due: date )

**Comment by ioana-chiorean** [comment]
Agenda is up! https://public.etherpad-mozilla.org/p/remo-call-24-03-16

**Comment by ioana-chiorean** [comment]
@couci - what do u think if we check some leaders' progress on their goals and invite them to share more? https://github.com/mozilla/participation-leaders-accountability/issues

**Comment by couci** [comment]
that's an awesome idea @ioana-chiorean ! Will definitely do :)
