### ISSUE TITLE
 Reps Weekly Call - March 31st, 2016 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#401]
# Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

⬅️ #391 
➡️ #402 
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] Council updates - (@ Reps Council, [medium], Due: date )
- [x] Events - (@francjp, [medium], Due: date )
- [x] Help me with my project - call for entries (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x]  ✅ Topic 1 - Events Playbook (@ioana-chiorean [medium], Due: March 30th) - Details #339 & #394 by @francjp
- [x] ❌ Topic 2 - Plan for community spaces (@ioana-chiorean [medium], Due: March 30th) - Details #313 by @williamq 
- [x] ❌ Topic 3 - "Bootstrapping your project" event kit for Connected Devices (@ioana-chiorean [medium], Due: March 30th) - Details #319 by @williamq @ensowhat 
- [x]  ✅ Topic 4 - Mozilla Tunisia Updates by @ZaafouriFF (@ioana-chiorean [medium], Due:March 30th) Details: https://github.com/mozilla/participation-leaders-accountability/issues/53 and https://github.com/mozilla/participation-leaders-accountability/issues/47 and https://github.com/mozilla/participation-leaders-accountability/issues/48 
- [x] ❌ Topic 5 - WebVR news by @end3r  and @rabimba (@ioana-chiorean [medium], Due: March 30th) Details: https://github.com/mozilla/participation-leaders-accountability/issues/23 and https://github.com/mozilla/participation-leaders-accountability/issues/12
- [x] ❌ Topic 6 - MozPH Participation Portal by @fayetandog (@couci [medium], Due: March 30th) - Details: https://github.com/mozilla/participation-leaders-accountability/issues/33

Status
🔜  - we can present next week
🔃 - we need to see when we can present
✅ - topic will be presented in the call
❔ -  topic needs to be confirmed for the call. 
❌ - not gonna be presented in the call. 
## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-31-03-16) (@ioana-chiorean, [small], Due: March 24th )
- [x] [Discourse post](https://discourse.mozilla-community.org/t/weekly-call-2016-03-31/7852) (@ioana-chiorean, @couci, [small], Due: date )
- [x] mail on reps- general (@ioana-chiorean, @couci, [small], Due: date )
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Send invites to speakers (@ioana-chiorean, @couci, [small], Due: date )
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Post meeting notes (@ioana-chiorean, @couci, [small], Due: date )
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean, @couci, [small], Due: date )

**Comment by couci** [comment]
added technical contributors topic, @francjp topics will be presented in next call since he is currently on PTO

**Comment by ioana-chiorean** [comment]
wrong issue miss @couci :dancers:

**Comment by couci** [comment]
oups sorry miss, changing again

**Comment by ioana-chiorean** [comment]
Agenda is up! https://public.etherpad-mozilla.org/p/remo-call-31-03-16 :tada:

**Comment by ioana-chiorean** [comment]
Notes here: https://discourse.mozilla-community.org/t/weekly-call-2016-04-07/7957/2
All done!
