### ISSUE TITLE
Reps Weekly Call - April 14th, 2016

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/participation-org#403]
## Goal:
- Organize the weekly reps call. 
## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 
## Related Issues & Links:

⬅️ #402 
➡️ #404
## Roles:

Owner: @ioana-chiorean
Involved: @couci 
## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] Council updates - (@ Reps Council, [medium], Due: date )
- [x] Events - (@francjp, [medium], Due: date )
- [x] Help me with my project - call for entries (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] ❌ Topic 1 - Plan for community spaces (@ioana-chiorean [medium], Due:  ) - Details #313 by @williamq 
- [x] ❌ Topic 2 - "Bootstrapping your project" event kit for Connected Devices (@ioana-chiorean [medium], Due:  ) - Details #319 by @williamq @ensowhat 
- [x] ❌ Topic 3 - WebVR news by @end3r  and @rabimba (@ioana-chiorean [medium], Due:  ) Details: https://github.com/mozilla/participation-leaders-accountability/issues/23 and https://github.com/mozilla/participation-leaders-accountability/issues/12
- [x] ❌ Topic 4 - MozPH Participation Portal by @fayetandog (@couci [medium], Due:  ) - Details: https://github.com/mozilla/participation-leaders-accountability/issues/33
- [x] ✅ Topic 5 - Reps Council/Peers/Participation joint meeting - Nuke
- [x] ✅ Topic 6 - Last Chance to Sign-Up for Take Back The Web Campaign!
- [x] ✅ Topic 7 - Quick CEL update - Rosana + Andre

Status
🔜  - we can present next week
🔃 - we need to see when we can present
✅ - topic will be presented in the call
❔ -  topic needs to be confirmed for the call. 
❌ - not gonna be presented in the call. 
## Pre-call checklist:
- [x] [Etherpad](https://public.etherpad-mozilla.org/p/remo-call-14-04-16) (@ioana-chiorean, @couci, [small], Due: date )
- [x] [Discourse post](https://discourse.mozilla-community.org/t/weekly-call-2016-04-14/8086) (@ioana-chiorean, @couci, [small], Due: date )
- [x] mail on reps- general (@ioana-chiorean, @couci, [small], Due: date )
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Send invites to speakers (@ioana-chiorean, @couci, [small], Due: date )
## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Post meeting notes (@ioana-chiorean, @couci, [small], Due: date )
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean, @couci, [small], Due: date )

**Comment by ioana-chiorean** [comment]
Notes: https://discourse.mozilla-community.org/t/weekly-call-2016-04-14/8086/2
