### ISSUE TITLE
Reps alignment and review team are implemented and initial comms plan drafted

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#409]
## Objective Goal:

Reps alignment and review team are implemented and initial comms plan drafted
- Responsible: @couci @nukeador @francjp Council
- Accountable: @rosanardila 
- Supporter: @deimidis @emmairwin 
- Consulted: @rosanardila 
- Informed: Reps

Supporting: [O4KR2](https://docs.google.com/spreadsheets/d/14v_8OajXaaqxdBQZp1w5-fyj3OaotB0Ra6Y-QJ8vtoM/edit?pref=2&pli=1#gid=198884355) _"Reps program successfuly implements alignement, mentoring and resources changes with broad agreement"_
## Sub-Goal Success:
- [ ] [Alignment WG](https://github.com/mozilla/Reps/issues/4) and [Review Team for resources track](https://github.com/mozilla/Reps/issues/1) implemented (R: @couci @nukeador Council)
- [ ] [First draft for changes comms](https://github.com/mozilla/Reps/issues/9) (R:@couci @nukeador Council S: @emmairwin @deimidis )
- [ ] [Plan for Council in London is created and resources/dependencies identified](https://github.com/mozilla/Reps/issues/11) (R: @couci @nukeador @rosanardila S: @deimidis)
## Related Issues & Links:
- [Mozilla Reps repo](https://github.com/mozilla/Reps/issues/)

**Comment by couci** [comment]
Updated the description in order to have RASCI for subgoals and added the related links

**Comment by ioana-chiorean** [comment]
Informed:  mentors -> all reps?

**Comment by emmairwin** [comment]
there's something between supporter and informed -this is an dependency for task in #410 , and getting the language right to extended community leaders will be important .

**Comment by nukeador** [comment]
@emmairwin Sorry, I don't get what you mean.

**Comment by nukeador** [comment]
I've updated all sub-tasks with their issues at the Reps repo.

**Comment by nukeador** [comment]
Most action items are almost done, probably we'll need next week to finish them.

**Comment by nukeador** [comment]
We will continue in #419
