### ISSUE TITLE
H3: Whistler work week: Finalize Participation sessions/presence + Pre-ww communication to volunteers and team leaders

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#41]
# Project Description

Roughly, this is about getting both the Participation Team and rest of the organization (related to volunteers and Participation) setup for the Whistler work week.

Previous Heartbeat #18 
# Primary Goals & Objectives for This Heartbeat
- Participation Team is setup for success at Whistler (agenda finalized, session + space design, alignment of team, skill-building)
  - Radical Participation Salon setup - external experts have role framed, logistics taken care of, framing, invites are out to the rest of the organization
  - Participation design sessions framed and offered
- All MoCo/MoFo teams are setup for successful volunteer engagement during the work week
- Volunteers have been surveyed prior to the work week
- Last-minute volunteer logistics are handled smoothly + we're ready to respond in a service oriented way to inevitable stuff that will go wrong
# Milestones
- [x] Kickoff Meeting
- [x] Standup Meeting
- [ ] Wrap-up Meeting
- [x] Invites out to various teams for Salon and Design sessions - June 3 (@geroter)
- [x] Agenda/goals finalization with Participation Team - June 5 (@geroter)
- [x] Basic "volunteer engagement tips" email out to team leaders + setup office hours for before the end of the Heartbeat - June 5 (@francjp)
- [ ] All logistics handled for external experts - June 5 (@francjp)
- [x] Design thinking skill-building framed for Participation Team - June 5 (@emmairwin)
- [ ] Design sessions identified/framed, teams contacted - June 12 (Natalie and @geroter)
- [x] Participation Team space plan - June 12 (@emmairwin)
- [ ] Plan finalized for engaging and prepping external experts - June 12 (Natalie)
- [x] Pre-workweek survey out to all volunteers - June 12 (@brianking)
- [x] Skill building completed by Participation Team - June 17 (@emmairwin)
- [ ] All sessions have a basic outline/design - June 19 (@geroter)
- [ ] Best practices "guide" for volunteers completed and out to teams - June 19 (@brianking)
- [ ] All volunteer logistic challenges are resolved + plan in place for last-minute problems - June 19 (@francjp)
- [ ] Analysis of volunteer survey (@brianking) - June 19
- [ ] Making the space thing happen - buying/ordering materials, plan for setup, etc. (@emmairwin) - June 19
- [ ] Additional communication to volunteers + Reps Council (@brianking) - June 19
- [ ] Communicating Whistler opportunities to non-attendees - June 19 (@geroter)
# Roles

Owner: @brianking 
Member: @geroter, @francjp, @emmairwin

**Comment by geroter** [comment]
@emmairwin Virtual Crash Course in Design Thinking:
http://dschool.stanford.edu/dgift/

**Comment by geroter** [comment]
Final invites went out:
https://docs.google.com/document/d/1roRewXhAZJx9afBOmutkAOcVVjFLGEFUhDn9fGodgMM/edit#heading=h.q0ohj0y36552

Here's a protected sheet with the groups/people the invites were sent to:
https://docs.google.com/spreadsheets/d/1YN5gILqzQb8Spx7L5kIAhEJoW_GtcR7NfrtnkkQDJM0/edit#gid=2077049223

**Comment by brianking** [comment]
I'm working on the team leads email and the initial setup email for volunteers, as well as the survery. Drafts coming soon.

**Comment by brianking** [comment]
Draft for team leads:
https://docs.google.com/document/d/1aPVC5tMwwiBqSdGDrW0FMGBWfh35w1Jp3oAnNsCtYh8/edit?usp=sharing
Please review and suggest edits.

@geroter have any of your communications targeted the volunteers coming yet? I think what we need to do there is:
- general logistics reminders
- reminder of sched tool
- information about the participation sessions (what the best doc to share?)
- anything else?

**Comment by geroter** [comment]
@francjp is duplicating Brian's efforts here:
https://participation.etherpad.mozilla.org/whistler2015-tips

**Comment by geroter** [comment]
The invite to the Radical Participation session went out to all volunteers.

Volunteer comms:
- As part of the communication to all volunteers (if we are doing any), I think we should let them know that our aim as a Participation team is to have the functional/product teams really be point people on their Whistler experience, with us playing a supporting role.
- We should also suggest that there will be some opportunities with the Participation team -- we will be setting up a creative space that will allow them to dig into participation design for their communities

This brings up a bigger question: Should we be having a session with all volunteers, focused on community building specifically?

**Comment by brianking** [comment]
Letters to go out today to Team Lead and Volunteers:

https://docs.google.com/document/d/1aPVC5tMwwiBqSdGDrW0FMGBWfh35w1Jp3oAnNsCtYh8/edit?usp=sharing

@geroter @emmairwin  please review.

**Comment by emmairwin** [comment]
Design Thinking - Participation Version.  Draft Guide I would follow to lead this session.  @geroter interested if this basic challenge fits what you envisioned:  https://docs.google.com/document/d/1ecMiOj-_9G5FNGyNCbljpg6zdgVX3WU_eDPtc2-2Fwg/edit#heading=h.8r0i6y1ipmtk

Your Mission: Redesign the volunteering experience for your partner.

**Comment by emmairwin** [comment]
@brianking looks good (sorry for late review)

**Comment by brianking** [comment]
Emails to team leads and volunteers went out today.

**Comment by emmairwin** [comment]
Started Participation Space - Draft, need feedback:  https://docs.google.com/document/d/1gV2jJlzCJa17IJE2cGIK1hnGujAgXkJtdhW8xe7KO1Y/edit?usp=sharing

**Comment by geroter** [comment]
Participation Salon/Expert Engagement draft:
https://docs.google.com/document/d/1mo-_kal0nwYqUoYfS3EXs0n6JMvmHwyme_S_2QsL5Rg/edit

**Comment by emmairwin** [comment]
latest draft of room complete and in need of feedback https://docs.google.com/document/d/1gV2jJlzCJa17IJE2cGIK1hnGujAgXkJtdhW8xe7KO1Y/edit#

**Comment by rosanardila** [comment]
hey team, is there going to be a guideline for volunteers joining the participation consulting teams? If volunteers can't join their team session and come to participation, is there a quick way to loop them in? Many thanks!

**Comment by emmairwin** [comment]
@francjp @brianking how can we know when volunteers have arrived?

**Comment by francjp** [comment]
@rosanardila we are working on best practices, I don't know if that would be what you are looking for
@emmairwin we have an spreadsheet with all volunteers arrival times. I've already shared this with Rubén. If you need something else, let me know.

**Comment by emmairwin** [comment]
material needs can go here:  https://participation.etherpad.mozilla.org/whistler-materials

**Comment by emmairwin** [comment]
*Ensure all volunteers have a buddy/contact on the team  in areas we see ourselves needing help with, or being able to identify opportunities for)

 1) Ask Volunteers to make sure their calendars are (continually) up to date with all sessions and other events they plan to attend
 2) Ask them to share that calendar with their buddy.
 3) Ask them to keep an eye out for  calendar-invitations (even at last minute) .

**Comment by brianking** [comment]
Best Practices, first pass:

https://docs.google.com/document/d/11KYoPDMKEH7TCteZJ7xeks4Dcd_vECiBkqZdMHeqoBU/edit?usp=sharing

Feedback and additions welcome.
