### ISSUE TITLE
Campaign is underway and we're learning and prepared for the end of the campaign. 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#412]
## Objective Goal:

Campaign is underway, coaches and mentors are active and establishing relationships, we're communicating well, aligning with community and ready for the future. 

R:@lucyeoh 
A: @bacharakis @deimidis, @emmairwin , @brianking @kpars270 @charissalaisy
C: Marshall, Urmika, Stacy, Sara, Jochai, Chris Riley
I: @ruben 
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/Campus-Campaign
## Sub-Goal Success:
- [x] All staff mentors have had 4 calls with their coaches, local coaches have had 3 weekly check-ins with their teams. Coaches feel engaged and invested in their teams and their team progress and we have criteria for National Coach Applicants. ( @deimidis  @lucyeoh)
- [ ] Teams have submitted 3 reports and 500 teams are active. (@luceyoh + 270)
- [x] We have a back-end dashboard set-up that clearly communicates global progress to goal. (Due May 6th)  ( @charissalaisy @bacharakis)
- [x] We have created and shared 8 educational materials and gathered feedback and learnings each. We have all materials prepped for the last 2 weeks of the campaign. ( @kpars270 @emmairwin )
- [x] Comms plan is established and 75% communications have already been sent out. 500 people understand the progress of the campaign.  ( @charissalaisy @bacharakis )
- [x] A plan for the process of shaping the future of Mozilla on campus is created and shared to the input groups. (@bacharakis)

**Comment by LucyeoH-zz** [comment]
200 Active Teams
