### ISSUE TITLE
New Community Spaces are on a path to setup

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#416]
## Objective Goal:

We are closer to choosing a space in Berlin that both volunteers and staff align on, and we have defined the full set of criteria for our "innovation spaces" in India

R: @ensowhat, @brianking
A: @brianking
C: @geroter, Innovation team
I:
## Tasks & To Dos Related to This Project:
- https://github.com/mozilla/community-spaces
## Sub-Goal Success:
- [x] Berlin: Staff and volunteer have met to share and talk about the community space (R: @ensowhat A: @geroter C: Mozilla Berlin staff and volunteers I: )
- [ ] Berlin: A shortlist of spaces are ready for final decision. and a draft move-in and programming plan is created (R: @ensowhat A: @geroter  C: I: ) 
- [ ] India: Gather initial set of requirements for the space(s) and open up first round of submissions (R: @brianking A: @brianking C: I: ) 
### Berlin
- https://public.etherpad-mozilla.org/p/MozillaSpaceBerlinManifesto
- https://public.etherpad-mozilla.org/p/MozillaSpaceBrainstorming

**Comment by ensowhat** [comment]
https://public.etherpad-mozilla.org/p/BerlinCommunitySpaceDiscussion_2016-05-02 to be updated

**Comment by ensowhat** [comment]
Volunteers + staff met and aligned their views on the goals and criteria.
- https://public.etherpad-mozilla.org/p/BerlinCommunitySpaceDiscussion_2016-05-13

List of spaces will be reviewed next week and visit organized.
- https://public.etherpad-mozilla.org/p/BerlinCommunitySpaceSpaces

**Comment by brianking** [comment]
Continued in #424 and #427.

Plans for other spaces are being halted for now as we evaluate the program in general.
