### ISSUE TITLE
Important parts of B2G OS are volunteers owned

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#417]
## Objective Goal:

B2G OS volunteers own all non-technical modules and are involved in technical modules.

R: @ensowhat
A: @geroter @brianking 
C: Smartphone Code Transition Team 
I:
## Tasks & To Dos Related to This Project:

[B2G OS Transition dashboard](https://docs.google.com/spreadsheets/d/1W-Vb9XOmoAKGWQXkJquTGPUb69NdmpJBVW1VXGFF2x8/edit?usp=sharing)
## Sub-Goal Success:
- [x] All working groups are volunteer owned.
- [x] 6 volunteer contributors are involved on technical modules. (R: @ensowhat A: C: Smartphone Code Transition Team I: )
- [x] All working groups have at least 3 volunteer contributors. (R: @ensowhat A: C: B2G OS Volunteer Community I: ) 
- [x] B2G OS meeting are owned by volunteers.  (R: @ensowhat B2G OS Volunteer Community A: C: @brianking  I: ) 
  "
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by ensowhat** [comment]
Technical working groups encounter difficulties to find volunteer owners, due to lack of skills.

**Comment by ioana-chiorean** [comment]
Hey @ensowhat and @brianking - is this something we can share in the Weekly reps call? Maybe can have a better visibility for the working groups and we will find the right people. cc @couci

**Comment by ensowhat** [comment]
Thanks @ioana-chiorean here's a list of the working groups:
https://wiki.mozilla.org/B2G/Transition_Project/Working_Groups
I'll keep you posted!
