### ISSUE TITLE
B2G OS communication is crystal clear and documentation answers most questions.

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#418]
## Objective Goal:

Status on the project is constantly clear thanks to a good communication

R: @ensowhat
A: @geroter @brianking 
C: B2G OS Communication Working Group
I:
## Tasks & To Dos Related to This Project:
- [B2G OS Transition dashboard](https://docs.google.com/spreadsheets/d/1W-Vb9XOmoAKGWQXkJquTGPUb69NdmpJBVW1VXGFF2x8/edit?usp=sharing)
## Sub-Goal Success:
- [x] Regular meetings ongoing, co-hosted by owners. (R: @ensowhat A: C: Working groups owners I: ) 
- [x] Weekly status updates are posted on Discourse and sent to stakeholders. (R: @ensowhat A: C: I: ) 
- [x] Wiki is up to date and helpful to new contributors (R: @ensowhat A: C: Documentation and communication working groups I: )
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by ensowhat** [comment]
Weekly meetings on going for each working group.
Weekly participation status posted and send.
Wiki and documentation up to date (or archived).

**Comment by ioana-chiorean** [comment]
Hey @ensowhat and @brianking - is this something we can share in the Weekly reps call? I think people will be interested to hear how this developed further. cc @couci
