### ISSUE TITLE
H3: FxAndroid in India: 4 experiments have detailed strategies, actions plans and teams in place

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#42]
# Project Description

Working with the 4-5 experiment teams that have come together in India around Firefox for Android, supporting their strategy development, with project management, in setting up for a learning/experimental agenda, and being a conduit to staff team members in MoCo.

Previous Heartbeat #11 

This is the main reference doc:
https://participation.etherpad.mozilla.org/fennec-india-team
# Primary Goals & Objectives for This Heartbeat
- At least 3 of the experiments on Firefox for Android in India have completed strategies and action plans
  - Ready to start implementation before the end of June
  - Volunteers remain squarely in the driver's seat
  - Ensure these are setup for measurement
- The approach we've taken is well-documented/lessons captured -- able to demonstrate this at Whistler
# Milestones
- [x] Kickoff Meeting
- [ ] Standup Meeting
- [ ] Wrap-up Meeting
- [x] One Participation Team member assigned as a champion for each experiment + have been in touch with teams - June 5 (@geroter)
- [x] All experiments have had their next planning meeting with clear next steps - June 9
- [x] Draft strategies/action plans circulated amongst team members and staff members - June 12
- [ ] Final strategies/action plans circulated to India community - June 19
# Roles

Owner: @geroter
Member: @deimidis, @brianking, @rosanardila

**Comment by geroter** [comment]
Experiment Champion job description for Participation Team member:

1) Keep momentum in the experiment -- meetings, to-dos, tasks, document management, etc
2) Help volunteers clarify/synthesize strategy and plans -- take notes, prepare strategy documents/decks, etc
3) Connect volunteer teams with relevant staff in the project -- keep this synchronized and grounded
4) Ensure that each initiative is taking an 'experimental' approach -- small and testing and learning vs. all about implementation and walking away

**Comment by geroter** [comment]
## Assignment of Champions
1. Firefox for Android Marathi = @geroter
2. FSA marketing challenge = @brianking 
3. Firefox Mini = @deimidis + @rosanardila 
4. Social media campaign/messaging = @rosanardila 

New... = @geroter
- Firefox .apk download on the https://www.mozilla.org/en-US/firefox/new/ 
- Home panel
- Equal rating

**Comment by geroter** [comment]
Good meeting with Marathi ... will be summarizing into draft strategy/plan:
https://etherpad.mozilla.org/Firefox-for-Android-Marathi

**Comment by brianking** [comment]
Meeting scheduled Thursday with TJ and Akshay.

**Comment by emmairwin** [comment]
@brianking  Akshay is also the community manager at Marketpulse, can you bring up with TJ outreach to Africa for data collection for Firefox OS as well ( different heartbeat, but still a p1 ).  If possible, because Akshay can 'action' the outcome

**Comment by anivar** [comment]
@geroter  I can plan a pilot on Firefox OS Malayalam , with out team

**Comment by anivar** [comment]
@geroter @emmairwin  I am interested in associating with Fennec launch Experiment in Indian Languages , please guide .

**Comment by geroter** [comment]
@anivar You should get in touch with Suraj Kawade or Chandrakant Dhutadmal or Rajesh Ranjan as they are leading this initiative. Let me know if you need me to put you in touch.

**Comment by brianking** [comment]
@AkshayTiwari , TJ, and I met last week to discuss the Firefox OS Marketing Challenge. Notes here:
https://docs.google.com/document/d/1slzicOOLxX8d25yXjep9I5_xHftHCJAv0ryFlhyjB-I/edit?usp=sharing

There is not a clear plan/path yet, we will spend some time this week digging in more.

**Comment by rosanardila** [comment]
The Fennec "mini" team had a meeting with some new members form Bangladesh, @deimidis attended it. I will be talking today to Margaret Leibovic and make sure to connect the volunteer team with the Fennec engineers before the end of the week.

We have been documenting the project status and updates here: https://participation.etherpad.mozilla.org/firefox-mini

**Comment by anivar** [comment]
@geroter Thank you . I already initiated a mailthread with Rajesh and Chandrakanth  cc'ing you
