### ISSUE TITLE
Insights from the campaign are ready for London and we have options for the Future of Mozilla on Campus ready for input. 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#422]
## Objective Goal:

Teams and Coaches are prepared to wind-down or understand their options for continuing through July 15th, insights from the campaign are ready to be shared in London, options for the Future of Campus have been drafted and are ready for input. 

R:@lucyeoh
A: @bacharakis @deimidis, @emmairwin , @brianking @kpars270 @charissalaisy
C: Marshall, Urmika, Stacy, Sara, Jochai, Chris Riley
I: @ruben
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/Campus-Campaign
## Sub-Goal Success:
- [x] All staff mentors will have communicated the extension and done a wrap-up with coaches who are not carrying on. All active local coaches will have communicated the extension and have reported on their plans to continue. ( @charissalaisy @deimidis )
- [ ] Will have increased the number of completed scavenger hunt activities from 91 -> 200 June 10  ( @charissalaisy @lucyeoh) 
- [x] All metrics captured in the dashboard are analyzed a debrief presentation is prepared for London. ( @charissalaisy @kpars270) 
- [x] A review and accessment of each core educational material is captured in the final survey. (@emmairwin @kpars270) 
- [ ] Wrap-up communications have gone out to major lists and 1000 people clearly understand the outcomes of the campaign. London Volunteers are ready to share their stories in London.  (@bacharakis @charissalaisy )
- [x] We have completed the listening and synthesis phases of the process and we have identified ""options"" by London. (@lucyeoh @bacharakis @kpars270) 
## Related Issues & Links:
#412

**Comment by LucyeoH-zz** [comment]
Wrap-up communications have gone out to major lists and 1000 people clearly understand the outcomes of the campaign. London Volunteers are ready to share their stories in London. (@bacharakis @charissalaisy )
- > extended the campaign so push this to after London

**Comment by LucyeoH-zz** [comment]
We have completed the listening and synthesis phases of the process and we have identified ""options"" by London. (@lucyeoh @bacharakis @kpars270) 

-> Will have ppl build options in London

**Comment by karanverma** [comment]
What is the web address for that?

**Comment by LucyeoH-zz** [comment]
All metrics captured in the dashboard are analyzed a debrief presentation is prepared for London. ( @charissalaisy @kpars270)  - > Waiting on week 7 reports.
