### ISSUE TITLE
The Participation software and systems program is visible, has a clear shared strategy with IT, user requirements and project definition for each of the pieces, and has a few "beta" pieces delivered

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#425]
## Objective Goal:

The Participation software and systems program is visible, has a clear shared strategy with IT, user requirements and project definition for each of the pieces, and has a few "beta" pieces delivered

R: @ppapadeas @geroter @hcondei @akilroy @CaptainCalliope 
A: @davidascher 
C: @rosanardila @nukeador 
I: Quite a long list here not in GitHub
## Tasks & To Dos Related to This Project:

https://wiki.mozilla.org/ParticipationSystems
## Sub-Goal Success:
- [x] Program visibility - Program wiki (including all the projects) is fully up to date and understandable by a broad audience (R: @CaptainCalliope @ppapadeas @geroter @davidascher @akilroy A: @hcondei C: I: )
- [ ] Discourse evolution - User stories and requirements completed with quotes from possible contractors (R: @CaptainCalliope A: C: I: )
- [ ] Volunteer Management Systems - Engaged a broad set of stakeholders on key user stories and options for moving forward, including some basic visual stories --> more of these conversations in London. Have priority Reps Portal feature/functions and a roadmap (R: @ppapadeas @akilroy A: C: I: )
- [x] Participation Metrics -  Have a working beta of a contribution dashboard. "Participation data" ready to present in London and engage with each org/VP on this. We have a few hypotheses we're prioritizing to "move" community sentiment + have done one more update to that qualitative data. (R: @geroter @couci @ppapadeas A: @geroter C: I: )
- [ ] Access for non-staff mozillians to documents and collaborative tools, Mozilla identity - We have a clear, shared overall strategy with IT (R: @ppapadeas @davidascher A: @davidascher  C: I: )
- [ ] Contributor compute infrastructure plan - TBD (R: A: @ppapadeas C: I: )

**Comment by LucyeoH** [comment]
- [ ] Wiki subgoal...

**Comment by LucyeoH-zz** [comment]
Flag: Super ambitious, needs to be broken out across several heartbeats moving forward.
