### ISSUE TITLE
The path to first time contribution on B2G OS is an highway

### ISSUE THREAD

**Issue by ensowhat** [mozilla/participation-org#426]
## Objective Goal:

Documentation and communication resources are accessible, clear and reviewed. The barrier for first time contribution is lowered.

R: @ensowhat B2G OS Community
A: @geroter 
C: @brianking 
I:
## Tasks & To Dos Related to This Project:
- https://wiki.mozilla.org/B2G/Transition_Project/FAQ
- https://docs.google.com/presentation/d/1YuQaLr-hiduT5xyT4TaiaUDYOsZAnmadduevAE6MOKo/edit?usp=sharing
- https://wiki.mozilla.org/B2G
- https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS
## Sub-Goal Success:
- [x] FAQ is reviewed  (R: A: C: I: ) 
- [x] Wiki has a main page with clear information (R: A: C: I: ) 
- [x] Guide for first first technical contribution is finished(R: A: C: I: ) 
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by ensowhat** [comment]
FAQ is here, finished at 100%: https://wiki.mozilla.org/B2G/Transition_Project/FAQ 
Getting Started guide is here, finished at 85%: https://docs.google.com/presentation/d/1YuQaLr-hiduT5xyT4TaiaUDYOsZAnmadduevAE6MOKo/edit?usp=sharing
B2G OS main page to live here, (work on going) : https://wiki.mozilla.org/B2G_OS

**Comment by ensowhat** [comment]
B2G OS main page to live here : https://wiki.mozilla.org/B2G_OS

**Comment by brianking** [comment]
Next steps here for next heartbeat are:
- Public communication about the transition period being over.
- Figure out Participation team support to give to this project, if any, over the next weeks and months.

**Comment by brianking** [comment]
Notes from London meeting:
https://docs.google.com/document/d/1EtDrXGbG4AryYPb3CYM3g3QtK8DMnDvYa3whxSbpnD0/edit?usp=sharing

Next steps, for another heartbeat, are above. Closing this one.
