### ISSUE TITLE
H3: Deliver v0.5 of Participation plan for Q2 and beyond

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#43]
# Project Description

One objective in the [Participation Strategic Plan](https://docs.google.com/document/d/1--rxHVg7Sscrlgxf1XV1Xb54BLmxvlbwNn1WzgEt2os/edit) was to "Develop a bold long-term plan for radical participation at Mozilla." To accomplish this, we have setup for having a [Participation Lab](https://wiki.mozilla.org/Participation/Lab) to explore three areas:
1. Core contributors
2. Connecting people to each other and Mozilla's mission
3. Organizational structure and processes

The experiments we have underway, along with the work in Q1/Q2 on the Reps program and Regional communities, put us in a position to start to articulate a direction for 1-Core contributors. For the other two areas, we are ready to articulate some questions and possible ways to invest, and are aiming to prioritize bringing an expert group together over the coming months to explore this space.
# Primary Goals & Objectives for This Heartbeat
- Have a deck/document that frames draft plans, ideas or questions in the 3 areas of exploration for Participation at Mozilla
  - Tested/feedback with Mark, Mitchell and the Participation Team
  - Sets up for a series of conversations at Whistler
- Expert group (inside and outside of Mozilla) is assembled and setup to contribute at Whistler
# Milestones
- [x] Kickoff Meeting
- [ ] Standup Meeting
- [ ] Wrap-up Meeting
- [x] Early first draft of ideas framed - June 9 (@geroter)
- [x] First round of feedback conversations complete - June 12 (@geroter)
- [x] Expert group - initial membership created and role framed - June 12 (@geroter, Natalie) 
- [ ] Expert group setup for Whistler/first conversations - June 18 (@geroter, Natalie)
- [ ] Second draft of deck/document - June 19 (@geroter)
# Roles

Owner: @geroter
Member: Mark, Mitchell and all Participation Team
