### ISSUE TITLE
All elements of the software program have a clear roadmap, responsibilities and resource requirements for Q3, with buy-in from all stakeholders

### ISSUE THREAD

**Issue by geroter** [mozilla/participation-org#433]
## Objective Goal:

Quarterly Objective: O5 all KRs

All elements of the software program have a clear roadmap, responsibilities and resource requirements for Q3, with buy-in from all stakeholders

R: @ppapadeas @geroter @hcondei @akilroy @CaptainCalliope @hmitsch 
A: @geroter
C: @rosanardila @nukeador 
I: Quite a long list here not in GitHub
## Tasks & To Dos Related to This Project:

https://wiki.mozilla.org/ParticipationSystems
## Sub-Goal Success:
- [ ] Have a solid v1 dashboard for contribution metrics, with conversations setup with every part of the org. (R: @geroter @ppapadeas A: @geroter C: participation team I: )
- [ ] We have a few hypotheses we're prioritizing to "move" community sentiment + have done one more update to that qualitative data. (R: @couci @geroter A: @geroter C: @nukeador @deimidis I: )
## Related Issues & Links:
#425

**Comment by a-kilroy** [comment]
Sub Goal Success:
- [ ] Formalize London presentation for approval to move forward on proposed recommendations
- [ ] Maker Party Event software plan
- [ ] IAM user stories and use cases
