### ISSUE TITLE
The Campus Campaign is wrapped up and we have a plan for building out phase 2

### ISSUE THREAD

**Issue by bacharakis** [mozilla/participation-org#434]
## Objective Goal:

By the end of this heartbeat everyone will have a clear view on what happened/lessons learned during the Campus Campaign. We will also have built a set of options and identified the next steps for the future of Mozilla on campus.

R: @LucyeoH 
A:  @bacharakis @kpars270 @charissalaisy
C: 
I: @geroter 
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/Campus-Campaign
## Sub-Goal Success:
- [x] Gather all the necessary information/data/photos/videos due to Friday 24/6 (@bacharakis, @kpars270 @charissalaisy) 
- [x] Build a debrief presentation for the Campus Campaign (@bacharakis, @kpars270) 
- [ ] Send wrap-up communication to the Campus Campaign participants (@charissalaisy, @bacharakis)
- [x] Identify/build options for the Future of Mozilla on Campus based on what was built in London (@LucyeoH,  @bacharakis, @kpars270 @charissalaisy) 
- [ ] Identify the next steps and a plan for building the Campus program out of the selected option (@LucyeoH,  @bacharakis, @kpars270 @charissalaisy)
## Related Issues & Links:

TBA
