### ISSUE TITLE
Community Spaces - Dev Engagement Program Evaluated and OKRs for Q3 Finalised

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#435]
## Objective Goal:

Show and evaluate numbers since April and determine next steps for the developer engagement program, while at the same time finalising some overall OKRs for spaces in Q3.

R: @brianking, @jmswisher 
A: @geroter 
C: 
I:
## Tasks & To Dos Related to This Project:
- London Notes: https://docs.google.com/document/d/1hEm029DeJBLuOSEK7btPMsLI3W_oq3IR1YISwcKML88/edit
## Sub-Goal Success:
- [x] Finalise OKRs for H2, as started in London (R: A: C: I: ) 
- [ ] Setup repository for sharing materials (R: A: C: I: ) 
- [ ] Mentor call for 2 more events types (Rust, Janitor) (R: A: C: I: ) 
- [ ] Review communications to developers (R: A: C: I: ) 
- [ ] Build out Metrics Dashboard (R: A: C: I: ) 
- [ ] Define status and roadmap for common surveys and platform (R: A: C: I: ) 
## Related Issues & Links:
- Previous issue: https://github.com/mozilla/participation-org/issues/424

**Comment by brianking** [comment]
Status:
- Finalise OKRs for H2, as started in London

Draft version here: https://docs.google.com/spreadsheets/d/152HaBX3TgZ_UuZ4OPWtdW1jXdjjqH8XH2pQWM8g46Vc/edit?usp=sharing
- Setup repository for sharing materials

Being discussed still in https://github.com/mozilla/community-spaces/issues/25
- Mentor call for 2 more events types (Rust, Janitor)

Times still being finalised
- Review communications to developers

TBD
- Build out Metrics Dashboard

Waiting on time of @couci 
- Define status and roadmap for common surveys and platform

Still being discussed in https://github.com/mozilla/community-spaces/issues/3
