### ISSUE TITLE
CD Volunteers are fully onboarded after London, and self-serve toolkit plan is defined

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#437]
## Objective Goal:

By the end of this heartbeat, we want to ensure that the volunteers who were in London (or were invited and could not come) are satisfied with the follow-up and are clear on next steps

R: @mikehenrty @brianking
A: @brianking
C:
I:
## Tasks & To Dos Related to This Project:
- Will be tracking at: https://github.com/mozilla/connected-devices/issues
## Sub-Goal Success:
- [ ] 1-1s (R: @mikehenrty @brianking A: C: I: ) 
- [ ] Run post-event survey (R: @mikehenrty @brianking A: C: I: ) 
- [ ] Start adding people to tools/comm channels we identified for CD team (R: @mikehenrty @brianking A: C: I: ) 
- [ ] Self-serve toolkit to run their own design/ideation workshops with their communities  (R: @mikehenrty @brianking A: C: I: )
- [x] Initial document published for evaluating CD events (R: @brianking @mikehenrty A: C: I: )

**Comment by brianking** [comment]
All tasks are filed and being tracked at https://github.com/mozilla/connected-devices/issues.

**Comment by brianking** [comment]
Check-in on the tasks:
- 1-1s : In progress, about 50% done. Mostly positive feedback so far.
- Run post-event survey : We've added our questions to the main Participation survey and are waiting for it to be published.
- Start adding people to tools/comm channels we identified for CD team : There is some low-hanging fruit here, such as posting regular updates about CD participation on Discourse.
- Self-serve toolkit to run their own design/ideation workshops with their communities : Just starting ... will likely host on github and build out bit by bit.
- Initial document published for evaluating CD events : Published:
  https://wiki.mozilla.org/Connected_Devices/Participation/Events/Evaluation
