### ISSUE TITLE
The Berlin Community is Setup for Q3

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#438]
## Objective Goal:

We are no longer pursuing a separate community space in Berlin, however we want to ensure that the community continues to have momentum. The goal here is for the community to be setup for and executes a successful TechWeekend IoT edition, and beyond that we define roles and activities to setup for Q3

R: @fiji-flo, @brianking, @mikehenrty
A: @geroter 
C:
I:
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:
- [x] Mozilla Tech Weekend: IoT Edition (2-3 Jul) is setup for success 1 (R: A: C: I: ) 
- [ ] Define roles for next 3 months (R: A: C: I: ) 
- [ ] Write out plan for next 3 months for the Berlin community (R: A: C: I: ) 
## Related Issues & Links:

(taken from issue #427 by @ensowhat)
#### Talk and get in touch
- Orga team Telegram group (invitation only)
- https://lists.mozilla.org/listinfo/community-berlin
- https://mozillians.org/en-US/group/berlin/

I recommend a public instant messaging channel, accessible to anybody to ask questions and get in touch easily.
#### Information
- The blog http://mozilla.berlin/

Recommendations: Ask Mario for access. Make time in meetings to choose updates about the Mozilla Berlin Community activities to publish here and on the …
#### Social Networks

Ask Brian about credentials for all these.
- https://twitter.com/mozillaberlin
- https://www.facebook.com/Mozilla-Berlin-417762471753823/

See also:
- https://twitter.com/mozillade
- https://twitter.com/mozilla_deutsch
- https://www.facebook.com/mozilla.de/
- http://www.meetup.com/Rust-Berlin/
- https://twitter.com/rustberlin
#### Event communication/organization:
- http://www.meetup.com/Berlin-Mozilla-Meetup/
- For other events: http://www.eventbrite.com/o/mozilla-berlin-10663488541
#### Mozilla Berlin Community organized events
- Mozilla Tech Weekend: IoT Edition (2-3 Jul)
  https://public.etherpad-mozilla.org/p/MozillaTechWeekend_2016-07-02
- [Ongoing] Open Mozilla Nights : http://www.meetup.com/Berlin-Mozilla-Meetup/
- Take advantage of the tech scene excitement in Berlin in September to organize an event around the 17 Sept? 

Recommendation : define areas where we are the most excited to build, project we want to launch and/or contribute to and plan events accordingly. Get closer to our friend organizations, hackerspaces, tech companies in Berlin to work and organize with them.
#### Mozilla Berlin Community to participate to …
- View Source Conference (12-14 Sept) https://viewsourceconf.org/berlin-2016/
- Codemotion Berlin (24-25 Oct) http://berlin2016.codemotionworld.com/
  Being organized with Francisco Picolini

Recommendations: Have an etherpad (or something else) to drop interesting links and do a regular review in meeting.

**Comment by mikehenrty** [comment]
@LucyeoH Do we want to close this? We did not finish everything in this issue.

**Comment by LucyeoH-zz** [comment]
Hey Michael,

As we're kicking off a new heartbeat the unclosed pieces can either be
transferred to a new issue, or you can re-open it and re-assign it to the
next milestone.

Cheers,
Lucy

On Tue, Jul 19, 2016 at 11:21 AM, Michael Henretty <notifications@github.com
