### ISSUE TITLE
The Campus Program is working closely with stakeholders to start building the structures and systems needed to open registration September 1st

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#439]
## Objective Goal:

The Campus Program has stakeholder alignment, a clear strategy and structure, and has started building the registration and onboarding processes. Invested groups are informed and engaged. 

R: Lucy 
A: Lucy & Christos
C: Campus Advisory Committee, Maker Party Committee, MoFo
I:
## Tasks & To Dos Related to This Project:

Follow along on our weekly progress [here](https://github.com/mozilla/campus-campaign#boards?repos=52040403)
## Sub-Goal Success:

_Stakeholder Alignement:_
- [x] Have a clear idea of roles & responsibility Mofo & Participation, and how we'll work together (Lucy)
- [x] We've had the first meeting of the Campus Advisory Committee, they know what the role of the committee is, they know the plan and have provided feedback (Christos) 
- [ ] A strategic plan is signed off on by all stakeholders and is communicated to all invested groups (Lucy)

_Infrastructure for Registration:_ 
- [ ] A technical strategy is agreed upon and resources are sourced. (Lucy) 
- [ ] We have sign-off on the programmatic structures and the registration form, we know which tool we'll use to collect information  (Lucy) 
- [x] Role description for regional coordinators is completed and clear (Christos) 
- [ ] We have a clear plan for reporting structures for regional coordinators (Christos) 

_Invested Group Communication:_
- [ ] Invested groups (FSAs, Reps, RALs, Campus Campaigners) understand the development of the progress and what to expect from now until Sept 1 (Christos) 

_Onboarding, Training, Activity Design:_
- [ ] A draft of Regional Coordinator onboarding is complete (Lucy & Christos) 
- [ ] Maker Party activities suitable for the program are identified (Lucy)

**Comment by LucyeoH-zz** [comment]
Blocked by final strategy sign-off.
