### ISSUE TITLE
Logistics and content for community gatherings are in place, and dates for 2 gatherings are defined

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#442]
## Objective Goal:

Dates, logistics and content for at least 2 Community Gatherings are ready and in place

R: @francjp @deimidis 
A: @nukeador 
S: @couci, @nukeador
C: @geroter 
I: Participation Team
## Tasks & To Dos Related to This Project:

Supporting O1: A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives.
## Sub-Goal Success:
- [x] Define dates and location for at least 2 Community Gatherings (R: @francjp A: @francjp  C: @geroter I: Participation Team ) 
- [ ] Prepare selection process and registration form (R: @francjp A: @nukeador C: P. Team I: P. Team ) 
- [ ] Content reviewed and ready to be shipped (R: @deimidis A: @nukeador C: P. Team I: P. Team ) 
- [ ] Logistics are in place, reviewed and secured (R: @francjp A: @francjp C: @nukeador, @deimidis I: P. Team ) 
## Related Issues & Links:
#430, #411, #421
