### ISSUE TITLE
The Q3 Activity Campaign launches, surfacing some up the most important contribution opportunties and activating our core base

### ISSUE THREAD

**Issue by brianking** [mozilla/participation-org#443]
## Objective Goal:

Launch the Activity Campaign with the micro-site activate.mozilla.community, and spread awareness among Mozillians of some present and upcoming contribution opportunities that have impact.

R: @brianking, @nukeador 
A: @brianking
C: @geroter 
I:
## Tasks & To Dos Related to This Project:
- Github Project, task tracker: https://github.com/mozilla/activate.mozilla.community
## Sub-Goal Success:
- [x] Design, code, host, and launch the activate.mozilla.community site    (R: @nukeador @brianking A: @brianking C: I: ) 
- [x] Build Comms plan for launch of campaign (R: @nukeador A: @brianking C: I: ) 
- [x] Align with Reps goals in terms of KPIs and activities on the portal  (R: @nukeador A: @brianking C: I: ) 
- [x] Launch 3 initial activities (R: @brianking A: @brianking C: I: ) 
- [x] Define roadmap for another 3 activities (R: @nukeador @brianking A: @brianking C: I: )

**Comment by brianking** [comment]
The site is up at https://activate.mozilla.community. We are blocked on offical launch by a few things.
- Process for budget swag
- How we track some KPIs and present the to participants
- Events system

Tracking at:
https://github.com/mozilla/activate.mozilla.community/issues

**Comment by karanverma** [comment]
Hi how can I involve into this activity?

**Comment by brianking** [comment]
Shipped!
http://brian.kingsonline.net/talk/2016/08/activate-mozilla/
