### ISSUE TITLE
The Campus Program has made substantial progress towards being ready for launch and is setting-up for success in both the short and long-term

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#444]
## Objective Goal:

The Campus Program is fully aligned with invested stakeholders, we are developing the required technical pieces, committed groups are updated, and we've begun developing an exciting on-boarding program. 

R:@lucyeoh @bacharakis 
A:@lucyeoh 
C: Mofo, Marketing, Legal, CAC
I:
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/Campus-Program
## Sub-Goal Success:

_Stakeholder Alignment:_
- [x] We have a common definition of what the Mozilla Club brand represents and how we'll represent the two programs with respect to it (Lucy)
- [x] The Campus Advisory Committee has provided feedback on the Regional Coordinator Role, the overall strategy, the outcomes and activities of the campaign and each region has a draft strategy for transition and outreach(Christos) 
- [x] Marketing has signed-off on sun-setting the FSA brand (Lucy)

_Infrastructure for Registration:_ 
- [x] A technical strategy is agreed upon, resources are sourced, and the site/page is under development.  (Lucy) 
- [x] The tool for registration is agreed upon and set-up  (Lucy) 
- [x] We have designed an onboarding process for Regional Coordinators (Christos) 
- [x] Reporting structures for RC's are set-up and we have a plan for reporting for Clubs generally (Christos) 

_Invested Group Communication:_
- [x] Invested groups (FSAs, Reps, RALs, Campus Campaigners) understand the development of the program, where they will fit and what to expect from now until Sept (Christos) 

_Onboarding, Training, Activity Design:_
- [x] A draft of onboarding is done (Lucy & Christos) 
- [x] We have identified activities for each of the impact areas (Lucy)

**Comment by ioana-chiorean** [comment]
Hey @LucyeoH and @bacharakis - when do u think we can present this in the reps call? cc @couci

**Comment by bacharakis** [comment]
Hi @ioana-chiorean ! We would like to broadly communicate this program as soon as we have all the details finalized, a website and an on-boarding process. 
We have already planned to share this to Reps, so except me in one of the future calls. I will mail you to schedule it as soon as everything is ready.

**Comment by ioana-chiorean** [comment]
Thanks @bacharakis ! 👍
