### ISSUE TITLE
Individual and Small Group Contributors have begun mobilizing their communities around Maker Party

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#445]
## Objective Goal:

There is a clear strategy for how individual and small groups will participate in Maker Party and EU individuals and small groups in our current network understand the campaign and have started mobilizing their communities to get involved.  

R: @lucyeoh @brianking @bacharakis 
A: @lucyeoh
C: 
I:
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:

_Strategic Alignment_ 
- [x] We have created a shared process for onboarding/recruiting with the Partner Team and are working closely aligned with the entire Maker Party committee (@lucyeoh) 

_EU Individuals and Small Group Contributors_  
- [ ] X EU community leaders (Reps and Regional Communities) commit to delivering a certain number of Maker Parties in their region.  ( @brianking )
- [x] Activated mobilizers have each had a one-on-one meeting with a staff members  ( @brianking )
- [x] Develop strategy support materials for mobilizers and community partners (@lucyeoh ) 
- [ ] Set-up support call schedule and strategy ( @brianking @lucyeoh) 

_Global Communities_ 
- [x] Global Communities for outreach are identified and know about MP and how to get involved (@lucyeoh) 
- [x] A strategy for the global version of activities is agreed upon and the work is delegated (@lucyeoh) 
## Related Issues & Links:

https://github.com/mozilla/part-MakerParty
