### ISSUE TITLE
EU and India community Gathering logistics and content are in place

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#446]
## Objective Goal:

Agenda, Content and logistics are  ready for the 2 community meet-ups

R: @francjp @deimidis 
A: @nukeador 
S: @couci @nukeador 
C: @geroter 
 I: Pareicipation team
## Tasks & To Dos Related to This Project:

Supporting Objective 1: A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives.
## Sub-Goal Success:
- [x] EU community gathering application form has been sent
  (R: @francjp C:@geroter, the participation team) 
- [x] Communication plan for EU community gathering has been created
  (R: @francjp S: @deimidis   C: @geroter, the participation team) 
- [x] Logistics and payments for community gatherings (India and Europe) have been secured (R: @francjp S: @couci C: I:@nukeador @geroter  ) 
- [ ] Agenda for EU and India community gatherings has been delivered (R: @deimidis S: @couci @C @geroter  ) 
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/442

**Comment by ioana-chiorean** [comment]
This will be nice to be announced in the Reps Call!

**Comment by couci** [comment]
I agree :) once @francjp makes the big announcement this week we can have a small announcement in the Reps Call next week as well :)

**Comment by brianking** [comment]
Anything I can do to help with the prep for the EU gathering?

**Comment by ioana-chiorean** [comment]
@couci - will u present both in this call ?  or just india?
@francjp - do you want to present EU maybe?

**Comment by couci** [comment]
@ioana-chiorean for India I would prefer to give a small announcement and have a recap of the meeting after the community meet-up
@francjp takes EU unless he is a daddy by then

**Comment by nukeador** [comment]
Agenda for India is on track.

Eu Gathering is on track, working on agenda during the next weeks.

Awesome work setting up everything! :D
