### ISSUE TITLE
First Cohort of coaches has been trained and the Leadership toolkit is ready to test

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#447]
## Objective Goal:

Leadership toolkit is ready and the first cohort have their own coachees

R: @deimidis @nukeador 
A: @nukeador 
S: @couci, @verenanz1, @xellpher
C: @geroter 
I:
## Tasks & To Dos Related to This Project:

Supporting: O2 "A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives."
## Sub-Goal Success:
- [ ] First Version (MVP) of the leadership toolkit has been finished and is online (R: @deimidis @nukeador  A: @nukeador S: @verenanz1, @xellpher) 
- [ ] Leadership toolkit resources are ready to be tested in India and Europe CG (R: @deimidis S: @ couci C:@geroter I: @nukeador  ) 
- [x] Coaching training first stage has been finished and coaches are starting to test their skills (R: @deimidis S:@nukedor, @couci C: Reps council I: Reps) 
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/441

**Comment by nukeador** [comment]
Coaches will start their coaching relationships next week on phase 2. Good work!

Leadership toolkit is not ready yet, we'll iterate in the following days to set a realistic roadmap for it.
