### ISSUE TITLE
Regional Coaches and the Review Team have started working

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#448]
## Objective Goal:

Regional Coaches team has started working in their regions after training while the Review Team is on a transition phase

R: @nukeador @couci
A: @nukeador @couci
S: @deimidis, @brianking ,@kelimutu review team
C: reps council
 I: Reps
## Tasks & To Dos Related to This Project:

Supporting O2: Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others.
## Sub-Goal Success:

_Regional Coaches_
- [x] Templates for Regional Coaches have been created and populated with the available info (R: @deimidis @nukeador  S: @Mte90 I:Reps ) 
- [x] First meeting with the Regional Coaches has happened (R: @deimidis @nukeador  S: @Mte90 I:Reps ) 

_Reps_
- [x] Council OKRs have been created with a focus on activity campaign (R:@nukeador, reps councilA:@nukeador S: @couci C: @bking I: Reps ) 
- [ ] Review Team has started acting on their transition responsibilities(R: @couci A:@couci S:review team, @kelimutu,  @nukeador  C: reps council I: Reps ) 
- [x] Communication plan for Reps  on Activity Campaign and how to get involved has been created (R:@nukeador @brianking  A: @nukeador S: @couci C:reps council ) 
- [x] Budget per initiative has been decided (R:@couci S:@nukeador  @kelimutu , review team, reps council C: I: ) 
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/440
https://github.com/mozilla/Reps/issues/1
[Transition plan](https://docs.google.com/document/d/115eCfi7W14O9q_iNbIX3oAb9XCTybfLHFTF_-yWF05s/edit#heading=h.53ehmot52ult)

**Comment by Mte90** [comment]
Last updates:
- The regional coaches started to fill the templates
- We are working on the first meeting agenda
- There will be two meetings for the timezones issues with all the coaches

**Comment by couci** [comment]
Budget allocation doc has been sent to the council for review and decision

**Comment by couci** [comment]
- Budget allocation has been decided, it needs to be communicated with the Reps.
- OKRs have been decided and council is voting on them

**Comment by Mte90** [comment]
Last updates:
- First meetings done
- Regional coaches started with the first activity to contact all the community and gather information like the status and the issues that they have

**Comment by nukeador** [comment]
Review team will start acting in the following weeks.

Everything else is done, great work everyone!
