### ISSUE TITLE
Reps.Coach program begins to expand and shape what Mozillians could make better to support Mozilla’s mission

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#449]
## Objective Goal:

Reps.Coach program evolves to second stage with first coach-coachee relationships, a second round of Reps and resources and activities are ready to take action.

R: @deimidis
A: @nukeador
C: @geroter
I: Reps Council

Supporting: [O1](https://docs.google.com/spreadsheets/d/1pR3DAlS32SB_RVBAM-595t4eXNU9fpWapwupQrQakYE/edit#gid=198884355) _"A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives."_
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:
- [x] First Reps.Coach cohort have their first coachee relationship, including at least one 1:1 conversation (R:@deimidis A:@council C: I: )
- [ ] A new Round of 24 Reps Mentors begins "Coach training" (R:@deimidis Reps Council A:@nukeador C: @brianking I: )
- [x] Leadership Toolkit has 5 training resources that Coaches and Reps could use to improve their skills (R: @nukeador @deimidis  A: C: I: )
