### ISSUE TITLE
Community Gatherings are planned and delivered with focus on alignment and skill training

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#450]
## Objective Goal:

Through Community Gatherings we bring skill learning and alignment to the communities.

R: @deimidis @nukeador
A: @nukeador 
S: @brianking @christos @ppapadeas
C: @geroter
I: 

Supporting: [O1](https://docs.google.com/spreadsheets/d/1pR3DAlS32SB_RVBAM-595t4eXNU9fpWapwupQrQakYE/edit#gid=198884355) _"A focus set of relevant training and learning opportunities for mobilizers are systematized and they regularly access these opportunities to be more effective in their contributions and as a result providing more impact to Mozilla’s main initiatives."_
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:
- [x] EU Gathering participants leave with plans to follow up with Maker Party, Activate Capaign and development of their communities (R: @brianking, @deimidis A: @nukeador C: I: )
- [x] Learnings from EU Gathering are reflected in a document (R:@brianking, @deimidis A:@nukeador C: I: )
- [ ] Learnings from India CG are incorporated to toolkits (R:@deimidis @couci A: C: I: )
- [ ] Sessions result from EU update CG toolkit/resources (R:@deimidis A:@nukeador C: I: )
- [x] Arabic CG: start logistic and selection process (R @deimidis: A:@nukeador C: I:@brianking @christos )
- [x] Arabic CG: Start flights and venue logistics (R:@nukeador, @deimidis A: C: I: )
