### ISSUE TITLE
Reps Regional coaches meet with communites and review team work improves budget performance

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#451]
## Objective Goal:

Reps Regional coaches meet with communities and review team work improves budget performance

R: @nukeador @couci 
A: @nukeador
S: @deimidis
C:
I:

Supporting: [O2](https://docs.google.com/spreadsheets/d/1pR3DAlS32SB_RVBAM-595t4eXNU9fpWapwupQrQakYE/edit#gid=198884355) _"Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others."_
## Tasks & To Dos Related to This Project:

[Reps Repo](https://github.com/mozilla/Reps/issues/68)
## Sub-Goal Success:
- [x] Regional coaches complete community meetings and deliver a report (R: @nukeador)
- [ ] Initial research on community feeling after the meetings (Initial trend) (R: @nukeador)
- [x] Activate Mozilla: Push for comms around getting involved and get more key people to lead (R: @nukeador @couci)
- [x] Council elections and on boarding happen (R: @nukeador @couci)
- [x] Review team: Comms delivered (R: @couci)
- [x] Review team: Infra in place (portal voting, bugzilla) (R: @couci Kiki)
- [x] Review team: Metrics to get an initial trend by the end of the quarter (R: @couci Kiki)
## Related Issues & Links:

[Reference meta issues and past issues] #
