### ISSUE TITLE
Campus Clubs is establishing a clear direction for 2017, strengthenings our offerings and building a strong community of trained and active leaders on campuses around the world!

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#452]
## Objective Goal:

We're establishing a clear direction for 2017 and beyond, we are improving our support structures and activities to better support leaders and participants, our community of trained and active individuals is growing consistently

R:@lucyeoh @bacharakis 
A:@lucyeoh @emmairwin 
C: Mofo, CAC, George
I: Reps, Major Lists, Internal 
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/Campus-Program
## Sub-Goal Success:

_Stakeholder Alignment:_
- [ ] We have strong alignment on a target-market strategy. (Lucy)
- [ ] CAC members are connected with active Regional Coordinators with their region, are implementing their year plans and have been assessed (Christos)
- [ ] We have new collaborations with Servo, Rust and Innovation (re: prizes)  (Lucy) 
- [ ] We have identified a potential collaborator and are exploring the relationship (Lucy)
- [ ] We have started contracted a researcher for the US (Lucy) 

_Infrastructure:_ 
- [ ] A map is available on the website listing active leaders (Christos + Nikos) 
- [ ]  the designer has started reviewing the site and proposed improvements for H2 (Lucy) 
- [ ] We have a requirements list for 2017 for our tracking and data processing needs.  (Lucy + Christos) 
- [ ] Our registration process has a strong cadence of communication (Christos) 

_Strong Campus Leaders:_
- [ ] Regional Coordinators - 50% C1- RC's have completed the trainig. All active RC's from C1 are partnered with Club Capatains. C2- RC's have started training. (Christos) 
- [ ] Club Captains - They have received at least 2 communications, and the first group is partnered with RC's (Christos) 

_Onboarding, Training, Activity Design:_
- [ ] Resources - Poster template, tracking members, and the letter are resources available on the website. (Christos) 
- [ ] Training - Emma reviews training program and has list of recommendations. ( @emmairwin )
- [ ] Activities - 2 new activities are published to the website (Christos) 

_FSA Transition_ 
- [ ] All FSA things on the web have transition messaging attached and a shutdown/archive/redirect date. (Christos)
