### ISSUE TITLE
Community mobilizers are actively participating in and supporting the Maker Party efforts in the EU

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/participation-org#453]
## Objective Goal:

Maker Party contributors in the EU are well-supported by staff and mobilizers who are hosting partner events, running events in their communities, encouraging and supporting their networks to run events.

R: @lucyeoh @brianking 
A: @lucyeoh
C:
I:
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/part-MakerParty/
## Sub-Goal Success:

**Hosts are Supported** 
- [x] Mobilizers support partner events in Poland and Vienna ( @brianking )
- [x] Mobilizers are well supported by staff through weekly office hours, update emails, and webinars ( @lucyeoh @brianking)

**EU Mobilizers and Hosts**
- [x] 30 community events are listed in nationbuilder ( @brianking ) 
- [x] 10 new mobilizers are added to our list ( @lucyeoh ) 

**Communities are Informed**
- [x] Maker Party blog post goes live (after website launch) 
- [x] Reps are aware of how to participate in Global events
