### ISSUE TITLE
Reps: Follow up plans for Regional communities and budget metrics/allocation delivered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#454]
## Objective Goal:

Reps Regional coaches meet with communities and review team work improves budget performance

R: @nukeador @couci 
A: @nukeador
S: @deimidis @brianking
C:
I:

Supporting: [O12](https://docs.google.com/spreadsheets/d/1Fs4cEpJVyA0PLJ1xybDQB6piGFY1fVHKCUS6Sh75SKI/edit#gid=198884355) _"Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others."_
## Tasks & To Dos Related to This Project:

[Reps Repo](https://github.com/mozilla/Reps/issues/)
## Sub-Goal Success:
- [x] Regional coaches access training on coaching and conflict resolution (R: @nukeador)
- [ ] ~~Next steps for communities that Regional Coaches have met are identified.  (R: @nukeador)~~ (didn't happen this HB)
- [ ] ~~At least 1-2 communities start contributing to focus initiatives. (R: @nukeador)~~ (didn't happen this HB)
- [ ] ~~Placeholder for activity campaign support from Reps. (R: @brianking)~~ (didn't happen this HB)
- [x] [Reps Budget allocation delivered](https://github.com/mozilla/Reps/issues/83) (R: @couci)
- [x] Baseline metrics for budget in place (R:  @couci)
- [ ] ~~Initial summary and draft timeline to merge all RepsNext fronts (R: @nukeador)~~ (didn't happen)
- [x] Initial meeting and coordination for Events strategy. (R: @nukeador)
## Related Issues & Links:
- [Last HB](https://github.com/mozilla/participation-org/issues/451)

**Comment by couci** [comment]
Budget allocation can be tracked here: https://github.com/mozilla/Reps/issues/83

**Comment by nukeador** [comment]
@brianking is there something we can still do this week to support activate campaign? We are pushing from the Regional Coaches front, but maybe something to push from the new Reps mentors (ping @deimidis)

**Comment by couci** [comment]
Baseline metrics delivered, first visualisation here: https://datastudio.google.com/u/0/#/org//reporting/0B8afomu5khGpaVJQbmxGOEs4VXM/page/TQy
Baseline on budget review has been decided based on last 12 months: 7.8 days
Goal for the next 3 months:**5.46** days

**Comment by couci** [comment]
Budget allocation for Q4 has been delivered, FAQ can be found [here](https://discourse.mozilla-community.org/t/q4-budget-allocation-the-faq/11618)
Also we published a [report](https://datastudio.google.com/u/0/#/org//reporting/0B8afomu5khGpeEdvRnlHWDdyeW8/page/REy) for October

**Comment by nukeador** [comment]
Updated with what happened and what didn't and we should move to the next one.
