### ISSUE TITLE
Community Gatherings are delivered to align communities with Mozilla and Participation Team goals, and volunteers received training on skills needed to mobilized others

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#455]
## Objective Goal:

Arabic Community Gathering is delivered and we start organizing Mexico Community Gathering

R: @deimidis @francjp
A: @nukeador
C: @emmairwin, @brianking, @ppapadeas,  @bacharakis
I:
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:
- [x] Logistics for Arabic CG are ready (R: @francjp A: @nukeador C: I: @deimidis )
- [x] Content for Arabic CG is ready and reviewed by the team (R: @deimidis A: @nukeador C: I: )
- [x] Mexico CG announcement is made (R: @deimidis A: @nukeador C: I: )
- [x] Mexico CG logistics begins  (R: @francjp A:@nukeador C: I:@deimidis )
- [x] Mexico CG functional teams invited defined (R: @deimidis A: @nukeador C: I: )
## Related Issues & Links:

[Reference meta issues and past issues] #

**Comment by francjp** [comment]
Updating issue. Mexico preparations has started, and logitistics for Arabic are ready to go.
