### ISSUE TITLE
A set of resources and procedures are ready to be used by mobilizers and Reps Mentor continue to received Coaching training 

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#456]
## Objective Goal:

A focus set of relevant resources for mobilizers are systematized, a draft standard process for producing, reviewing and measuring content is ready and Reps Mentors received training on coaching skills with a better shape guide.

R: @emmairwin @deimidis
A: @nukeador @reps_council
C: @nukeador @verena @mikko @greg
I:
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/reps-regional/issues  

https://github.com/emmairwin/leadership_toolkit
### Coaching framework
- [ ] 24 Reps mentors begins Coach training (R: @deimidis A: @council C: @nukeador I: )
- [ ] «Coaching guide» received an update on content and structure (R: @deimidis A: @nukeador C: @emmairwin I: )
### Coaching

- [ ] Reps Mentors continue training on Coaching skills using a better shape and structure guide. 
#### Standards

- [ ] Together with community, standards for content development, testing and feedback are defined and documented.
### Measuring

- [ ] As part of standards documentation, we have a first draft of a process for evaluating, and implementing feedback . (but we're not doing it yet)
#### Content

- [ ] 5 quality learning resources are completed, and ready for testing & feedback as per quality assessment standards.
#### Framework

- [ ] Together with community, we have reviewed and iterated on a new version of the framework.
#### Website

- [ ] We have delivered specs for a leadership toolkit webiste to the participation systems team.

**Comment by nukeador** [comment]
@emmairwin Can we have the Leadership Toolkit tasks as a check list like coaching? Thanks!

**Comment by deimidis** [comment]
Update on people for the coach training. We have an initial new cohort of 12 current Mentors and we are discussing with Council about how we will be covering the other available places
