### ISSUE TITLE
We have proposed a light-weight roadmap for Participation D&I

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#459]
## Objective Goal:

Participation planning & experiments that test ways we can drive D&I ( first draft of plan, objective, 2017 plan for this work)

Phase 1 - Research & Findings

Phase 2 - Experiments

Phase 3 - Robust Volunteer-Facing Strategy

R: @emmairwin
A: @geroter 
C: @couci   @deimidis 
I:
## Tasks & To Dos Related to This Project:

Repo to come.
## Sub-Goal Success:
- [x] Together with Larissa, review D&I Strategy & set goals for participation alignment. 
- [x] Identify data we need for D&I , and gap analysis (research) of what we actually have .
- [ ] Identify and define 3 initiatives that build d&i alignment into participation, with experiments and ways for others to get involved (focus groups).  
- [ ] A light-weight roadmap is created.

**Comment by emmairwin** [comment]
Initiatives will come after research phase of roadmap which is 

Phase 1 - Research
Phase 2 - Experiments
Phase 3 - Robust volunteer facing strategy

Moving research and experimentation goals to HB #3
