### ISSUE TITLE
A standard  and strategy for documentation is proposed and we begin to implemnt

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#461]
## Objective Goal:

[List objective & link]

R: @emmairwin
A: @geroter 
C: @LucyeoH 
I:
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Sub-Goal Success:
- [ ] Update Participation Wiki including top 10 most relevant documents.
- [ ] Propose organizational structure, and collect feedback
- [ ] Create revised proposal based on feedback, and begin to implement.
