### ISSUE TITLE
Improve the functioning of the participation team through a series of research initiatives.

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#462]
## Objective Goal:

[List objective & link]

R: @emmairwin
A: @geroter @LucyeoH 
C: @nukeador @hmitsch 
I: participation team (experiments, wiki)
## Tasks & To Dos Related to This Project:

[Link to Repo, Spreadsheet, Trello etc.]
## Wiki Refresh - Sub-Goal Success:
- [x] Update Participation Wiki including top 10 most relevant documents.
- [x] Propose organizational structure, and collect feedback
- [ ] Create revised proposal based on feedback, and begin to implement.
## Participation Experiments - Sub-Goal Success:
- [x] A collection of high-level initiatives, their hypothesis, how we tested it, what we learned, and how that influences are work is documente.
## Community Manager Call Reboot - Sub-Goal Success:

*\* Think community of practice vrs community call**
- [ ] Outreach to past and potential participants of the community managers call (previously Participation call) to gain insights into value and potential value.
- [ ] External to Mozilla, investigate and research how other community manager calls bring value, excitement, engagement.
- [ ] Create an initial proposal for feedback.
## Research Volunteer Management Systems (VMS) - Sub-Goal Success:
- [x]  Research CRM and other methods with potential to effectively manage volunteers according to modeling Henrik has currently proposed

**Comment by LucyeoH-zz** [comment]
@emmairwin - I found an old Participation Call reboot call [here](https://docs.google.com/document/d/1D3I1lJSZZSkHqRUs_FxlHY2OiWGXQ1Vtqa5tizy2F3U/edit). Thought might be interesting.
