### ISSUE TITLE
A set of resources and procedures are ready to be used by mobilizers and Reps Mentor continue to receive Coaching training

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#466]
A set of resources and procedures are ready to be used by mobilizers and Reps Mentor continue to receive Coaching training
## Objective Goal:

A focus set of relevant resources for mobilizers are systematized, a draft standard process for producing, reviewing and measuring content is ready; Reps Mentors continue with their training on coaching skills and we start to acquire data about how participants evaluate this project.

R: @emmairwin @deimidis
A: @nukeador @reps_council
C: @nukeador @verena @mikko @greg
I:
## Tasks & To Dos Related to This Project:

https://github.com/mozilla/reps-regional/issues  
- [x] Together with working group, Learning outcomes, descriptions, audience for 10 resources have been generated and approved by Reps Team
- [x]  5 Learning personas have been generated (or identified from existing work), that drive our learning content outcomes.
- [x]  A process for review by Reps team of learning outcomes is documented and embraced.
- [ ] Regional and Rep Coaches have been briefed to the Leadership Toolkit content goals, and feel ready to introduce their communities to the opportunity of testing content for the initial release in December.
## Sub-Goal Success:
- [x] 12 Reps mentors begins Coach training (R: @deimidis A: @council C: @nukeador I: )
- [x] «Coaching guide» received an update on content and structure (R: @deimidis A: @nukeador C: @emmairwin I: )
- [ ] Interviews with Reps Coach 1st Cohort to understand how they are working with the tools they learned (R: @deimidis C: @nukeador I: )
- [ ] Interviews or survey to Coachees to know how they are feeling with their Coachs. (R: @deimidis c: @nukeador)

**Comment by deimidis** [comment]
- Interviews with Reps Coach 1st cohort was changed to a survey. They are still answering, so there's no report yet.
- I didn't advance on interviews with Coachees

**Comment by emmairwin** [comment]
All was completed except testing phase - it felt rushed.  going to focus on learning outcome and measurement in next heartbeat.
