### ISSUE TITLE
D&I Roadmap begins to take shape.

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#467]
## Objective Goal:

Identify data we need to effectively understand and grow diverse and inclusive communities, with a gap analysis of how we are currently meeting those needs, and recommendations for ensuring we do.

Participation planning & experiments that outline the ways test ways we can drive alignment with the D&I strategy are underway.

R: @emmairwin
A: @geroter 
C: @couci   @deimidis  @larissashapiro
I:
## Tasks & To Dos Related to This Project:

Repo to come.
## Sub-Goal Success:
- [x]  Diversity Data Documentation & Gap Analysis. 
- [ ] Identify and define 3 initiatives that build d&i alignment into participation, with experiments and ways for others to get involved (focus groups).  
- [ ] A light-weight roadmap is created.

**Comment by emmairwin** [comment]
This became a 'Plan for a D&I Strategy for Participation'

https://docs.google.com/document/d/1FkaTI6w5lzwidx6kYboggmaul-G1VFllXyP1szFerf4/edit#
