### ISSUE TITLE
Activate campaign plans for Reps have been defined and Resources track identity and next steps has been defined

### ISSUE THREAD

**Issue by couci** [mozilla/participation-org#468]
## Objective Goal:

Deliver a plan for reaching out Reps for activate campaign and advance on Reps Resources track

Supporting: [O12 ](https://docs.google.com/spreadsheets/d/1Fs4cEpJVyA0PLJ1xybDQB6piGFY1fVHKCUS6Sh75SKI/edit#gid=198884355)""Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others.
"

R: @nukeador @couci
A: @nukeador 
C: @deimidis @brianking @kelimuttu @fpicolini reps-coucil
 I: reps
## Tasks & To Dos Related to This Project:

[Reps Repo](https://github.com/mozilla/Reps/issues/)
## Sub-Goal Success from [previous HB](https://github.com/mozilla/participation-org/issues/454):
- [x] At least 1-2 communities start contributing to focus initiatives. (R: @nukeador ) 
- [x] Next steps for communities that Regional Coaches have met are identified
  (R:@ nukeador) 
- [ ] Initial summary and draft timeline to merge all RepsNext fronts (R:@nukeador ) 
## Sub-Goal Success from this HB:
- [x]  Sync and measure activate campaign data (R: @nukeador  @brianking )
- [ ]  Create a comms plan to reach out to Reps and get them to involve on activate campaign (R: @brianking  @nukeador )
- [x] Analyse and publish data Budget procedure data and define positive sentiment basis (R: @couci)
- [ ] Have a draft plan for EventsNext and start testing it with FOSDEM. (@nukedor)
- [ ] Gather training resources for Resources tracks and identify training needs (@couci)
- [ ] Document all Reps Resources Decisions and communicate them with Reps (@couci)
## Related Issues & Links:

https://github.com/mozilla/participation-org/issues/454

**Comment by geroter** [comment]
Humble suggestion: Create some competitive/social incentives for Reps. We have strong metrics for the campaign/activities. Let's use those to create a basic Reps Leaderboard, weekly call-outs, and maybe even small prizes for people in the top 5?

**Comment by nukeador** [comment]
Yes, @brianking and @comzeradd  were working on a leaderboard for activate site and the idea was to use it that way :-)

**Comment by nukeador** [comment]
Reference https://github.com/mozilla/activate.mozilla.community/issues/66

**Comment by couci** [comment]
Survey and results can be found here: http://discourse.mozilla-community.org/t/reps-budget-survey/11552
