### ISSUE TITLE
Arabic Community Gathering actions are finished, Mexico Community Gathering is delivered and planning for next year starts

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#470]
## Objective Goal:
Plan for Mexico Community Gathering is ready, content created and we begin preparations for Hawaii All Hands

R: @deimidis @francjp
A: @nukeador
C: @emmairwin
I:

## Tasks & To Dos Related to This Project:
[Link to Repo, Spreadsheet, Trello etc.]

## Sub-Goal Success:
- [x] Logistics for Mexico CG are ready (R: @francjp A: @nukeador C: I: @deimidis )
- [x] Content for Mexico CG is ready and reviewed by the team (R: @deimidis A: @nukeador C: I: )
- [ ] Plan for volunteer participation at Hawaii is ready (R: @francjp A:@nukeador C: I:@deimidis )
- [x] All Arabic CG actions are finished and debrief delivered (R: @deimidis A:@nukeador C: I:@fracjp )

## Related Issues & Links:
[Reference meta issues and past issues] #

**Comment by nukeador** [comment]
@deimidis We should have the follow-up for Arabic here too.

**Comment by francjp** [comment]
[Master Spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/11V57_hCGq26oFoQuRRD30hEb9W-DLHHaYCuboQ7T7sg/edit?usp=sharing) ready.

**Comment by ioana-chiorean** [comment]
Are there any public aftermath materials?
