### ISSUE TITLE
RepsNext implementation plan is ready and resources track has a solid list of training needs in order to support MozActivate end-of-year plan

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#472]
## Objective Goal: 
RepsNext implementation plan is ready and resources track has a solid list of training needs in order to support MozActivate end-of-year plan

Supporting [Participation Team O6](https://docs.google.com/spreadsheets/d/1Fs4cEpJVyA0PLJ1xybDQB6piGFY1fVHKCUS6Sh75SKI/edit#gid=198884355): _"Reps is the program for most core volunteers where many communities feel their voice represented and influencing the organization, and where mozillians join to be more aligned, grow their skills and be more impactful in mobilizing others."_

R: @couci @nukeador
A: @nukeador
C: Reps Council
I: @deimidis @brianking @francjp 

## Tasks & To Dos Related to This Project: 
* [Reps repo](https://waffle.io/mozilla/Reps)

## Sub-Goal Success:
- [x] Gather the existing training material for the Resources track (R: @couci, S: @kelimuttu) - O6KR3
- [x] Create a draft of the training needs for Resources track based on the persona of Resources Reps (R: @couci, S: @kelimuttu C: @deimidis) - O6KR3
- [x] Create a standard mechanism for communities to request local swag for MozActivate (R: @kelimuttu, S: @couci) - O6KR1
- [x] Initial summary and draft timeline to merge all RepsNext fronts (R:@nukeador ) - O6KR4
- [ ] Create a comms plan to reach out to Reps and get them to involve on activate campaign (R: @brianking @nukeador )	 - O6KR1
- [x] Advance EventsNext and draft a plan to test it at FOSDEM. (R: @nukedor S: @deimidis @brianking @francjp @couci ) - O6KR5

## Related Issues & Links: 
* https://github.com/mozilla/participation-org/issues/468

**Comment by couci** [comment]
existing training resources have been gathered here https://docs.google.com/document/d/1HXkEMLqy-BQDKAvzvimzp2i-OALKhyrp62lt-hdNUhI/edit
