### ISSUE TITLE
Leadership Toolkit is launched with most requested resources ready, Coach trainig is recognized as useful for Coach mentoring and ready to be taken asynchronously

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#473]
## Objective Goal: 
Leadership Toolkit is launched with most requested resources ready, Coach trainig is recognized as useful for Coach mentoring and ready to be taken asynchronously

R: @emmairwin @deimidis 
A: @nukeador 
C:
I:

## Tasks & To Dos Related to This Project: 
[Link to Repo, Spreadsheet, Trello etc.]

## Sub-Goal Success:
- [x] Review activity by 1st Reps Coach cohort and find numbers to know if they were active and using training tools (R: @deimidis) 
- [x] 2nd Reps Coach cohort finish their training and begin to use these new tools with their mentees (R: @deimidis)
- [x] There's a version for «Coaching guide» ready to be publishied on Leadership Toolkit website that Mozillians could use to learn these techniques asynchronously (R: @deimidis, A: @nukeador, C: @emmairwin)
- [x] Leadership toolkit website design ready (R: @emmairwin)

## Leadership Toolkit
- [x] 3 Prioritized resources are developed according to approved learning objectives and according to our QA and development workflow (R: @emmairwin)
- [x] 3 Existing, excellent resources are developed according to approved learning objectives
- [x] A plan for measuring and testing is developed and is implementable(? if that's a world) in finished content via our workflow process (R: @emmairwin)
- [x] Testing has begun in one community, as led by our working group leads for regional testing (R: @emmairwin @deimidis )
- [x] A plan for website  (design prototype) release in Hawaii is underway . (R: @emmairwin)

## Related Issues & Links: 
[Reference meta issues and past issues] #

**Comment by deimidis** [comment]
Has to be updated with @emmairwin information about Leadership Toolkit plans

**Comment by jgmac1106** [comment]
This looks like such a solid plan.

Clarification on asynchronously. Do you envision this to be self paced activities or in small cohorts of coaches?

Asking in terms of instructional design. Both are possible the latter is better.

**Comment by jgmac1106** [comment]
Another issue is deciding on the workflow for the learner for an asynchronous learning environments.

For asynchronous learning I like a hub (where the content lives), the learner's space (blog or portfolio), and the stream (where they share and talk)

Possible ecosystems:
- Discourse. Pro: easy, already exists, could leverage built in badges as assessment. Con: Are forums dead?
- Planets. Make an rss feed for posts and comments. Pro: Uses open and distributed web. Con: Uses open and distributed web.
- Wordpress. Pro: easy and available plug ins for learning environments. Con: php and wordpress talent not readily available in community. 
- Commercial. MoFo is using Teachable . Pro: Turn key, maybe cheaper. Con: Not FOSS

-Chat stream. Something like gitterhub, mattermos, or Telegramt. Pro: more temporal and webby. Con: content can be skipped over. Voices lost.
