### ISSUE TITLE
Community Gathering Playbooks are ready to be shared with a long and a short version

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#474]
## Objective Goal: 
Community Gatherings (EU, IN, MX, Arabic) follow-up plans are ready and in motion with clear consensus and playbook start being used

R: @nukeador 
A: @francjp, @deimidis, @emmairwin, @brianking, @psubhashish
C: @nukeador 
I: Reps and Mozillians

## Tasks & To Dos Related to This Project: 
[Playbook 2.0](https://docs.google.com/document/d/1Me6jN1S1zqRiHNtUttX-fZibuK1-uB_XHQbG4dYhHww/edit?usp=sharing)
[Content and Event planning](https://docs.google.com/document/d/1nxnm_LInRCoS87AIlgxcx8pJV9ukt2Ihx1WkxmElDkA/edit?usp=sharing)
[Short version](https://docs.google.com/presentation/d/1NpBh1nrcMmP704gidLle0TXIrEsn5YZLSTNOgh3qh0g/edit?usp=sharing)

## Sub-Goal Success:
- [x] Arabic Community plan after CG is clear and next steps and checkins are known by responsible people (R: @deimidis, A: @nukeador) OKR11K4
- [x] Mexico Community plans after CG are settled and next steps clear for responsible people (R: @deimidis, A: @nukeador) OKR11K4
- [x] Sylhet CG is ready to be approved by Council (R: @deimidis, C: @psubhashish) OKR11K5
- [ ] Initial guidance for EU planning is drafted, and Gathering attendees are informed of current thinking (R: @brianking) OKR11K4
- [x] India community restructuring and defining roles and accountabilities (4 sub-groups; Meta, Functional, Geographical and Focus) (R: @psubhashish) OKR11K4
- [x] Playbooks are ready with short and long versions (R: @francjp, @deimidis) OKR11K5

## Related Issues & Links: 
#

**Comment by ioana-chiorean** [comment]
Cool! Can't wait to read some!
