### ISSUE TITLE
Planning & preparation for Team & Volunteers is completed for Hawaii All Hands

### ISSUE THREAD

**Issue by emmairwin** [mozilla/participation-org#475]
## Objective Goal: 

R: @emmairwin  @francjp 
A: @geroter 
C: Participation Team Innovation Team
I: 

## Tasks & To Dos Related to This Project: 
[Link to Repo, Spreadsheet, Trello etc.]

## Sub-Goal Success:
- [ ] Weekly emails sent to Participation/Innovation Team, Volunteers and Staff working with volunteers (@emmairwin )
- [ ] All logistics for volunteers have been completed leading up to the All Hands 2 (R: @franc) 
- [ ] Team Schedule and room plan is completed, and entered into sched.  (@emmairwin )
- [ ] Team fun activities scheduled/planned or otherwise agreed upon  (@emmairwin )
- [ ] Session planned for 'All Volunteers' (@emmairwin @geroter )
- [ ] Volunteer coaching has been completed for all with invited volunteers (@emmairwin @deimidis )

## Related Issues & Links: 
[Reference meta issues and past issues] #
