### ISSUE TITLE
Improvements to the team dashboard

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#494]
## Objective Goal: 
Various improvements to the team metrics dashboard

## Related documents and links 
* [Dashboard](https://docs.google.com/spreadsheets/d/1-kQDO_4gPozcEt1wT2567DXVQ3VVH6Vpp-oypH3s7iE/edit#gid=1736363276)

## Item list:
- [ ] Tasks should link to the github issue
- [x] All tasks should be listed for one HB, to avoid closed ones to disappear.
- [x] No manual action should be needed even if we add 20 new issues today (plan for scaling)
- [x] Errors in main tab table should be hidden by default.
- [x] New rows added from zapier are parsed.
