### ISSUE TITLE
H3: Capture and synthesize feedback/lessons from the recent meetups

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#50]
# Project description

Lasts Hearbeats (issue #12) we created a template to create agenda and get feedbacks from Community meetups. This heartbeat we will analyze results from lasts Community meetups feedback and re-think our previous solution
# Primary Goals & Objectives for This Heartbeat
- [ ] Make a second version of our Feedback template
- [ ] Create a way to measure or collate feedback
# Milestones
- [x] Kickoff Meeting
- [x] Standup Meeting
- [x] Wrap-up Meeting
- [x] Analyze feedback from Africa Meetup
- [x] Analyze feedback from Balkans Meetup
- [x] Get feedback from Ecuador Community Meetup
- [x] Get feedback from Bangladesh Community Meetup
- [ ] Look at the overall results from the last community meetings and analyze it
- [ ] Create a way to see all data collected 
# Roles

owners: @deimidis @francjp 
member: @williamq

**Comment by francjp** [comment]
Contacted John Jensen from Metrics team to gather more feedback, and for ideas to apply to next surveys to see trends and spot differences.

**Comment by francjp** [comment]
Mozbalkans Post-report: https://docs.google.com/document/d/1bjWZAkOQ4vipoG2iG4s5OKgRq3a50XSwKVp7hotRsTE/edit?usp=sharing

**Comment by francjp** [comment]
Africa post-recap and next steps: https://docs.google.com/document/d/152BXKdJdz_BWVdGbrWUjh2__ZIIW40nisBlJR1FUhNU/edit?usp=sharing

**Comment by brianking** [comment]
@deimidis @francjp  Please edit this comment and fill out this template. Thanks!

### What was supposed to happen?

...

### What did happen?

...

### What we learned?

...

### What are some improvements?

...

### What does the next Heartbeat for this project look like?

...

**Comment by francjp** [comment]
## What was supposed to happen?

Create a template for collect feedback after events, also define a post-survey event to send after every community/inter-community meetup

## What did happen?

We had 3 post-survey, contacted the metrics team to see trends, and amended some questions in the template.

## What we learned?

Not all the meetups are the same, and doesn't cover the same issues. So we probably need to work on having a template for the meetups in order to finds trends. Also, we need to try to find a way to collect some "negative" comments, since the "free text" field can cover some, but generally all the comments were positive.

## What are some improvements?

Yes, we thought in implement a template for the agenda of a meetup. Also smaller and easy surveys are better to collect more responses.

## What does the next Heartbeat for this project look like?

We don't have future meetups in the following month, so probably we can work first on the agenda, or a template for the meetup, and then based on that review the post-survey, and create also a template for post-mortem.
