### ISSUE TITLE
Defining a roadmap for India community restructure

### ISSUE THREAD

**Issue by psubhashish** [mozilla/participation-org#513]
## Objective Goal: 
A roadmap to focus on other team tasks and communicate the India community about the next steps.

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Call with provisional meta team to discuss internally (scheduled on Wednesday) (R: @psubhashish )
- [x] Defining a clear roadmap based on the call with provisional meta team (R: @psubhashish )
- [x] Review and finalize the provisional meta team's decision (R: @LucyeoH )
- [x] Connecting teams with internal contacts within staff (R: @LucyeoH )
- [x] Communicate to the larger India community (R: @psubhashish )

## Related Issues
[Reference meta issues and past issues] #

**Comment by LucyeoH** [comment]
@psubhashish as per George's recommendation I'd suggest adding a

**Comment by LucyeoH-zz** [comment]
@psubhashish as per George's recommendation I'd add a piece in here around connecting teams with internal contacts within staff. Happy to support on that (help you find the right people).

**Comment by psubhashish** [comment]
@LucyeoH added and sent you an email about the same.

**Comment by psubhashish** [comment]
The provisional meta team is being [consulted](https://docs.google.com/document/d/1TlVI4wdFR0DzCk4WPnmB1iX-qRBvybIHm-6J2Jgvb-E/edit) about the public announcement and there will be a public announcement this week.

**Comment by psubhashish** [comment]
* Announced on mailing list and on [Discourse](https://discourse.mozilla-community.org/t/update-about-the-mozilla-india-community-restructuring/14786).
* The provisional meta team would recruit new members and graduate to the meta team (the process is explained in the Discourse post)
* The meta team will continue with the regular engagement (newsletter, monthly call) with the Indian community.
