### ISSUE TITLE
Q1HB2 project goals are delivered

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#522]
Project owners - please add a 2 sentence update to this issue with what you'll be working on in HB2. 

## Objective Goal: 
All project owners deliver their plans for HB2. 

## Item list:
- [x] Campus Clubs (R: @bacharakis)
- [x] Developer Communities (R: @LucyeoH)
- [x] Community Census (R: @nukeador)
- [x] Diversity and Inclusion (R: @emmairwin)
- [x] Community Participation Guidelines (R: @emmairwin)
- [ ] Mozilla Reps (+ Comms & Activate) (R: @couci)
- [ ] FOSDEM (R: @francjp)

**Comment by nukeador** [comment]
As a reminder to everyone, this needs to be delivered today EOD (PST) so it can be reviewed tomorrow mid-day (EU).

**Comment by nukeador** [comment]
As a test, let's use this issue to track it, instead of emails.

## Community Census

During HB2 we will finalize the feedback phase with stakeholders and engage with an external vendor to deal with the data gathering/analysis and market research. Realistically we'll need the full HB to come up with the vendor and align on needs and deliveries.

**Comment by LucyeoH-zz** [comment]
## Developer Marketing

During HB2 we'll continue to provide a consulting roll to developer marketing by providing feedback on the strategy document.

**Comment by emmairwin** [comment]
## Diversity & Inclusion 
Final iterations of qualitative & qualitative research are completed, with early themes identified, design sprint logistics finalized and sessions proposed.

https://github.com/mozilla/community-development/issues/523  
https://github.com/mozilla/community-development/issues/524
https://github.com/mozilla/community-development/issues/525

## Community Participation Guidelines
CPG draft is released and receiving early feedback from community via Discourse and Activate campaigns.

https://github.com/mozilla/community-development/issues/526

**Comment by bacharakis** [comment]
For Campus clubs we want to

- Finalize our Affiliate Clubs strategy,
- Develop an impactful activity for our students, 
- Start working on the requirements for building a challenge, 
- Build a monthly reporting mechanism for measuring our impact in communications, activities etc
- Improve our training, redesign our map and execute our communications plan
- Launch a research in India
- And generate a report based on the preliminary results of the US research

You can also find our objectives in this [doc](https://docs.google.com/spreadsheets/d/17Kkpq1wa3rFmIxkGpvKsKbD3rG563XiJZPbnQCUYsxs/edit#gid=2102446922) and this [repo](https://github.com/mozilla/community-development/issues?q=is%3Aopen+is%3Aissue+label%3A%22Campus+Clubs%22+milestone%3A%22Q1+HB2+-+March+3rd%2C+2017%22)

Cheers
