### ISSUE TITLE
H3: Support the Webmaker team for each of their P1 countries to have an actionable plan for Webmaker rollout

### ISSUE THREAD

**Issue by deimidis** [mozilla/participation-org#53]
# Project Description

Webmaker team is launching a new project in some markets (Brazil, Bangladesh, Indonesia and Kenya) and ask for our help to plan the work with volunteers.
# Primary Goals & Objectives for This Heartbeat
- [ ] Based on Webmaker App Playbook, create a plan and an agenda for Community meetups to create local launch plans
- [ ]  Create a playbook about Webmaker App deployment that could be use for other communities
# Milestones
- [ ] Work in the agenda and implementation of the plan in Bangladesh
- [x] Organize a meetup in Brazil to organize the community after this project
- [ ] Work to implement this project at Bangladesh and Brazil events
# Roles

owners: @williamq @deimidis

**Comment by deimidis** [comment]
update:

Workign with Bobby and Paul from Webmaker team to organize a first planification event in Brazil on June 14th. 8 community members will participate (invitation was sent to brazil mailing list and Discourse). 

We are planning a full day session, using part of the agenda and activities Laura used in Bangladesh. I will be going to the event and facilitate it.

**Comment by brianking** [comment]
The Bangladesh Webmaker sessions were mostly run by @LauraReynal with remote support from @secretrobotron. However, @rosanardila and I would like to help out here in whatever way we can.

Are there any documents yet that we can hack on?

**Comment by deimidis** [comment]
Webmaker App launch planning event was made this Sunday June 14th in Sao Paulo. Just 7 community members could participate. Agenda was created by @secretrobotron and @HPaulJohnson.

Works was good, with great discussion about what works and what not in the previous webmaker events. Also we had time to brainstorm and work in some Webmaker examples to show (and we found some bugs).

@panaggio just created all the issues on Webmaker-launch planning repository. On June 1th we will send an email to the Brazilian mailing list (and a post in discourse) reporting back to the community and asking for other participants to colaborate.

We define to make a Brazilian launch at FISL event, next Friday July 10th

**Comment by umeshagarwal** [comment]
Adding to this have planned to organizing an Online event on Webmaker App. 
Event Page: https://reps.mozilla.org/e/lets-learn-webmaker-for-android/

I have also created a presentation: http://bit.ly/1QPZQs3
Discussion on discourse : https://discourse.mozilla-community.org/t/webmaker-for-android-detailed-presentation/2450

**Comment by brianking** [comment]
@deimidis  Please edit this comment and fill out this template. Thanks!

### What was supposed to happen?

...

### What did happen?

...

### What we learned?

...

### What are some improvements?

...

### What does the next Heartbeat for this project look like?

...
