### ISSUE TITLE
H3: Implement a prodecure for volunteeers to discover and contribute to impactful initiatives around mozilla that are aligned with org goals

### ISSUE THREAD

**Issue by nukeador** [mozilla/participation-org#54]
## Project Description

Owner: @nukeador
Member: @deimidis @couci @rosanardila 

Implement a prodecure for volunteeers to discover and contribute to impactful initiatives around mozilla that are aligned with org goals.  See H2 for more project background #20  
## Primary Goals & Objectives for This Heartbeat
- Draft the specs of an "Initiatives Dashboard"
- Have a first version of this dashboard by the end of the Heartbeat
## Milestones
- [x] Kickoff Meeting
- [x] Standup Meeting
- [ ] Wrap-up Meeting
- [x] [Fri. June 4th] Draft specs about an "Initiatives Dashboard" https://docs.google.com/document/d/1HXF9WZwStrBVafTdUiWVF-WKEoOw09fXNlwgjPnHA2o/edit
- [x] [Fri. June 4th] Contact infrastructure team with the specs to know viability.
- [ ] [Thu. June 18th] First version of the dashboard deployed.

**Comment by nukeador** [comment]
@couci @deimidis @rosanardila I've started populating the doc, please add your thoughts by tomorrow (EOD)

https://docs.google.com/document/d/1HXF9WZwStrBVafTdUiWVF-WKEoOw09fXNlwgjPnHA2o/edit

**Comment by nukeador** [comment]
We are still waiting for Infrastructure team feedback. I've just sent them a second reminder.

**Comment by MajkenC** [comment]
This sounds like something is going to be built in-house. Is there also a plan to evaluate existing tools? I know CBT had tested one tool ages ago, but I forget the name. I also came across Switchboard (eg https://communitybuilders.switchboardhq.com/ ) last year.

**Comment by nukeador** [comment]
We are meeting tomorrow with infra team to analyze the problem we want to solve and the possible solutions we have. 

One comment from George we are going to consider for this heartbeat is:

"Spin up a Minimum Viable Product tool (i.e. a spreadsheet or Google Doc or 1-page website), and then test that very very quickly with a few communities to get feedback, and also to understand their needs better."

**Comment by nukeador** [comment]
After meeting with Pierros we decided to describe some user stories first on the doc and from there define a MVP for next week.

**Comment by nukeador** [comment]
Having the MVP this week is currently at risk. The asking for support and planning phases have taken way longer than we expected.

**Comment by MichaelKohler** [comment]
Does this include sharing Mozilla's top goals?

**Comment by nukeador** [comment]
@MichaelKohler That would be ideal for an updated version of this heartbeat

**Comment by nukeador** [comment]
### What was supposed to happen?

Implement a procedure for volunteers to discover and contribute to impactful initiatives around mozilla that are aligned with org goals.

### What did happen?

We defined how this ideal dashboard would look like but we were unable to build it. 

### What we learned?

We have little vision about the currant mozilla initiatives that have clear pathways for volunteers. We don't have a lot of resources for building our own dashboard without support from other parts of the team/other teams.

### What are some improvements?

We need to improve the response time within the team. We spent one week and a half asking and waiting for support from different stakeholders.

### What does the next Heartbeat for this project look like?

We should re-think completely this and turn it into a way people can learn what are the current org/areas goals and be trained on how to set-up their own initiatives to support them.Having a place to share them so other people can be inspired would be ideal.
