### ISSUE TITLE
Campus Club research in India

### ISSUE THREAD

**Issue by psubhashish** [mozilla/participation-org#543]
## Objective Goal: 
Create a database of premier institutes of India, contact details of student/staff-coordinators/professors, reach out to the student communities, have 20-30 students sign up to be interviewed for the research survey, interview some of them.

## Related documents and links 
* [Campus Club Indian students research Working doc](https://docs.google.com/document/d/1fpTYdW9K8O5v-RJ2HfBJQonh2vpAasWt4beawruGm4U/edit)

## Item list:
- [x] Create a [detailed plan](https://docs.google.com/document/d/1fpTYdW9K8O5v-RJ2HfBJQonh2vpAasWt4beawruGm4U/edit) for the entire research process (See more in issue [#329](https://github.com/mozilla/Campus-Program/issues/329))
- [x] University contact database creation, outreach and getting students signed up (see [#364](https://github.com/mozilla/Campus-Program/issues/364) (R: @psubhashish )
- [x] Screening applications, scheduling and conducting interviews (See more in issue [#371](https://github.com/mozilla/Campus-Program/issues/371)) (R: @psubhashish )
- [ ] <s>Documenting high level initial findings after interviews (R: @psubhashish )</s>

## Related Issues
* [#364](https://github.com/mozilla/Campus-Program/issues/364)
* [#329](https://github.com/mozilla/Campus-Program/issues/329)

**Comment by psubhashish** [comment]
Striking off the last expected outcome "Documenting high level initial findings after interviews" as the interviews could only happen during the last weekend as it took time for getting availability of students. More about the interviews are being captured [here](https://github.com/mozilla/Campus-Program/issues/382), and the findings are being [here](https://docs.google.com/document/d/1fpTYdW9K8O5v-RJ2HfBJQonh2vpAasWt4beawruGm4U/edit#heading=h.cgb5ht7muytn).
