### ISSUE TITLE
Project plan for Regional Coaches are ready and approved

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#546]
## Objective Goal: 
Create a project plan for Regional Coaches, aligned with team objectives for the year

## Related documents and links 
* [Draft document](https://docs.google.com/a/mozilla.com/document/d/1Do5bbi51YCUVG00JlVWzo8pJ7N6rP9MZB8TJ7b_mrGc/edit?usp=sharing)

## Item list:
- [x] Create a draft of project plan for Regional Coaches (R: @francjp, A: @nukeador)
- [x] Ask feedback to CDT team (R: @francjp)
- [x] Share document with Reps council (R: @francjp)

**Comment by francjp** [comment]
Document updated and shared with the council.
