### ISSUE TITLE
H3: Senegal / Tunisia participation experiments 

### ISSUE THREAD

**Issue by williamq** [mozilla/participation-org#56]
## Project Description

Owner: @williamq
Members: @brianking @geroter 

Continue implementing experiments around SUMO and Marketing for Fx OS that aim to test new approaches to community development. See H2 for more project background #21
## Primary Goals & Objectives for This Heartbeat
- all Senegal and Tunisia summer SUMO interns have received training and onboarding 
- Adopt a Store program launch plan finalized 
- draft agreement with jokkolabs finalized
## Milestones
- [x] Kickoff Meeting
- [ ] Set up call with Orange for AS
- [x] Set up call with MozillaSN for AS
- [x] Interview all SN and TN SUMO interns
- [x] Schedule a online training with SUMO team
- [ ] Draft first version of AS rollout plan + gather feedback from members 
- [ ] Draft final version of AS rollout plan
- [x] Schedule meeting with Karim Sy (Jokkolabs)
- [ ] Draft Jokkolabs agreement and get feedback
- [ ] Draft final version of agreement

**Comment by brianking** [comment]
Off topic but related, wondering if this is the sort of project we could hook into, e.g. to get contributions to Firefox OS:

http://mybroadband.co.za/news/general/128768-radical-new-free-computer-training-project-coming-to-south-africa.html

**Comment by brianking** [comment]
@williamq  Please edit this comment and fill out this template. Thanks!

### What was supposed to happen?

...

### What did happen?

...

### What we learned?

...

### What are some improvements?

...

### What does the next Heartbeat for this project look like?

...

**Comment by williamq** [comment]
## What was supposed to happen?
- Kickoff Meeting
- Set up call with Orange for AS
- Set up call with MozillaSN for AS
- Interview all SN and TN SUMO interns
- Schedule a online training with SUMO team
- Draft first version of AS rollout plan + gather feedback from members
- Draft final version of AS rollout plan
- Schedule meeting with Karim Sy (Jokkolabs)
- Draft Jokkolabs agreement and get feedback
- Draft final version of agreement

## What did happen?
- Kickoff Meeting
- Set up call with MozillaSN for AS
- Interview all SN and TN SUMO interns
- Schedule a online training with SUMO team
- Schedule meeting with Karim Sy (Jokkolabs)

## What we learned?
- feedback from SUMO team quite positive so far - it seems to verify our initial hypothesis that an internship format is increasing the quality and quantiy of contributions from contributors. The internship is only in its first 3 weeks so still very early in the game but the results are so far encouraging. 
- AS has been a bit more difficult to get off the ground, largely due to a lack of time plus there was Ramadan which slowed things down quite considerably. At the same time, it seems that Orange and local Egypt community have been working on their own AS program in Egypt. It will be interesting to see how this program evolves in Egypt. 
- a possible partnership with Jokkolabs is on hold as we figure out our priorities for Q3, namely around our community spaces. 

## What are some improvements?
- we need to establish a more systematic approach to working with Orange France. It's been difficult to figure out whether to work more closely with local Orange offices or to first work with the mother base in Paris. 

## What does the next Heartbeat for this project look like?
- if this is considered P1 for Q3, then we need to double down our efforts for the AS program to get it off the ground. Orange is clearly interested in this and Senegal and Tunisia are great testing grounds.
