### ISSUE TITLE
[Regional Coaches] Project Plan for Regional Coaches ready to share with Coaches and Communities

### ISSUE THREAD

**Issue by francjp** [mozilla/participation-org#568]
## Objective Goal: 
Project Plan for Regional Coaches aligned and ready to be shipped

## Related documents and links 
* [Project plan updated](https://docs.google.com/a/mozilla.com/document/d/1jbX6EGioyJ2bsXyAn-JwEDALhxHbDAUB_4qzUd9uWgI/edit?usp=sharing)

## Item list:
- [x] Get a final sign-off from Community Development team (R: @francjp)
- [x] Communication plan ready to kick-off the updated program (R: @francjp)
- [x] Regional coaches informed and aligned with the new plan (R: @francjp)

## Related Issues
#547
