### ISSUE TITLE
H3: Leadership training for Reps

### ISSUE THREAD

**Issue by rosanardila** [mozilla/participation-org#58]
# Project description

Following up on the Heartbeat 2 project around Reps leadership training this heartbeat aims to refine the previous planning for impact training and try two new different leadership workshops:
- Community empowerment workshop: the aim is to discover how Reps are currently empowering their communities, distill best practices and inform curriculum building.
- Mozilla Manifesto and Participation Guidelines: the aim is to connect volunteers with the Mozilla mission and show the actuality if the Manifesto, while at the same time making the connection between our manifesto and our participation guidelines evident. 
# Primary Goals/Objectives - Success Measures
- Refine the remote version of the planning for impact workshop, get 50% of mentors to go through it
- Test new leadership workshops
# Secondary Goals/Objectives
- Understand better how Reps are connected to regional/local communities and how they empower and lead other Mozillians
# Key hypotheses and how they will be tested
- As in heartbeat 2 we want to keep on testing if leadership workshops helps us change the goal setting process of Reps.
# Deliverables
- Version 0.2 of planning for impact workshop
- Version 0.1 of “Manifesto and Guidelines” workshop
- Version 0.1 of “Community empowerment” workshop
# Team

owner: @rosanardila
members: @brianking, @nukeador
informed: @williamq, @emmairwin 
# Milestones (complete before dates)
- [x] June 5th: Design and deliver “Manifesto and Guidelines” workshop in Bangladesh
- [x] June 8th: invite mentors to second round of “Planning for impact” workshop
- [x] June 8th: start discourse workshop “Community empowerment”
- [ ] June 15th: deliver second round of “planning for impact”
- [x] June 16th: remote session on “community empowerment” workshop
- [ ] June 18th: analyze surveys for planning for impact

**Comment by brianking** [comment]
@rosanardila  Please edit this comment and fill out this template. Thanks!

### What was supposed to happen?

...

### What did happen?

...

### What we learned?

...

### What are some improvements?

...

### What does the next Heartbeat for this project look like?

...
