### ISSUE TITLE
Heartbeat 1: Design new experience for One and Done suitable to first-time Mozillian prospects to test out Hypothesis 1 of bigger “Update and expand One and Done” Q2 goal

### ISSUE THREAD

**Issue by ppapadeas** [mozilla/participation-org#8]
# Project descritipion

One and Done is a tool (built by, but not restricted in utility to the QA team) to introduce new contributors to Mozilla by showing “easy” beginners tasks as a first step to getting more involved with teams.
# Why
- The concept of showcasing quick and relatively simple tasks for new is very promising. It could be heavily promoted in places like https://www.mozilla.org/en-US/contribute/.
- The site is promoted on /contribute within some of the ways to contribute, but it could definitely be more prominent as a one-click way to get started instead of picking an interest/area. RB
- However, the implementation has some limitations, some of which we should fix before experimenting with this from a broader Participation perspective.
# Primary Goals/Objectives
- item 1. **Some bold text.** _And some italics text._
- item 2
# Secondary Goals/Objectives
- item 1
- item 2
# Team
- Owner @ppapadeas 
- Members: @djst, ...
- Informed: ...
- Others: ...
# Milestones (complete before dates)
- [x] Set up planning meeting with stakeholders and align on overall plan (@djst, due May 12)
- [x] Evaluate existing research on this topic (@ppapadeas, due May 13)
- [ ] Sync with stakeholders to figure out next steps based on findings above (@djst, due May 14)
# References
- List any relevant documents, etc.

**Comment by djst** [comment]
- [x] a task list item
- [x] list syntax required, Owner: @djst, due May 8
- [x] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [x] completed

**Comment by ppapadeas** [comment]
lkdfj slkdfj
=======

sldfjs
------
