### ISSUE TITLE
Heartbeat 2: Design simplified mozilla.org/contribute/signup/ page and prepare for A/B testing

### ISSUE THREAD

**Issue by djst** [mozilla/participation-org#9]
Designing a simplified interface specifically tailored towards people new to Mozilla.
# Project descritipion

Designing a simplified interface specifically tailored towards people new to Mozilla, who want to contribute in some form (not donations) but not sure what they could be doing. 

The basic proposal is that we design an interface/layer/webpage that provides 1-3 easy choices and present this as the first thing someone sees when showing interest in contributing to Mozilla. This would then be A/B tested against the existing mozilla.org/contribute/signup page (the page you land on when clicking the big button on the /contribute page).
# Why
- more info soon
# Primary Goals/Objectives
- Design delivered (Holly)
- Page implemented (Participation Infrastructure)
# Secondary Goals/Objectives
- A/B testing infrastructure chosen, implemented
# Team
- Owner @djst 
- Members: @ppapadeas, Holly, Jen Bersch, 
- Informed: Mary Ellen, George
# Milestones (complete before dates)
- [x] Kickoff meeting (@djst, May 14)
- [x] Identify suitable first-time bugs (@djst, May 16)
- [x] Design wireframes (@holly, May 17)
- [ ] Develop Copy (@LucyeoH, May 29)
- [ ] Implementation (@comzeradd, May 29)
# References
- https://docs.google.com/document/d/1OAJ24FJyNj6aADKEmbAhMrhYFzJQ0cEvy2lp3jIkQB0/edit#

**Comment by comzeradd** [comment]
Bugzilla tracker for all 4 variations: https://bugzilla.mozilla.org/show_bug.cgi?id=1168359

Already started implementing the first variation

![signup](https://cloud.githubusercontent.com/assets/939357/7856997/f1417310-0535-11e5-84cb-4cc5817f0444.jpg)

**Comment by djst** [comment]
## What was supposed to happen?
- Scoping and identifying good first-time contributions for visitors of mozilla.org/contribute
- Delivery of wireframes/design for new mozilla.org/contribute/signup page
- Implementation of the above pages
- Ideally setting up A/B testing infrastructure

## What did happen?

The above, except implementation is not 100% finished (which is my responsibility for not staying on top of the project due to Engagement commitments all of last week).

## What did we learn?

We learned that the Brand Engagement team is a great partner on experimentation on www.mozilla.org and there's strong interest across the org to do better with these /contribute pages. 

## What are some improvements?

David (project manager) didn't stay on top of this project due to spending all of last week in SF with Engagement team (his other job). Other stars in the team took over (Emma and Lucy in particular), and we're having strong support from Jen and Holly on the Brand Engagement team, so we were still able to pull most of this off.

## What does the next Heartbeat for this project look like?

We should now actually launch the A/B tests and evaluate how the new design performs compared to the existing one. If the new design performs better, we should consider swapping the existing design out. We will also likely do more and deeper experimentation and learn more about what exactly leads to higher engagement on these pages, which types of first-time contributions are most suitable to present on the page, and other interesting facts about how new people discover how to contribute for Mozilla.
